
package com.asutp.okocits3.ueh.ws.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataGateService", targetNamespace = "http://ws.ueh.okocits3.asutp.com/", wsdlLocation = "http://localhost:8080/okocits3-ueh-ws/DataGate?wsdl")
public class DataGateService
    extends Service
{

    private final static URL DATAGATESERVICE_WSDL_LOCATION;
    private final static WebServiceException DATAGATESERVICE_EXCEPTION;
    private final static QName DATAGATESERVICE_QNAME = new QName("http://ws.ueh.okocits3.asutp.com/", "DataGateService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/okocits3-ueh-ws/DataGate?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAGATESERVICE_WSDL_LOCATION = url;
        DATAGATESERVICE_EXCEPTION = e;
    }

    public DataGateService() {
        super(__getWsdlLocation(), DATAGATESERVICE_QNAME);
    }

    public DataGateService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAGATESERVICE_QNAME, features);
    }

    public DataGateService(URL wsdlLocation) {
        super(wsdlLocation, DATAGATESERVICE_QNAME);
    }

    public DataGateService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAGATESERVICE_QNAME, features);
    }

    public DataGateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataGateService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataGate
     */
    @WebEndpoint(name = "DataGatePort")
    public DataGate getDataGatePort() {
        return super.getPort(new QName("http://ws.ueh.okocits3.asutp.com/", "DataGatePort"), DataGate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataGate
     */
    @WebEndpoint(name = "DataGatePort")
    public DataGate getDataGatePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.ueh.okocits3.asutp.com/", "DataGatePort"), DataGate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAGATESERVICE_EXCEPTION!= null) {
            throw DATAGATESERVICE_EXCEPTION;
        }
        return DATAGATESERVICE_WSDL_LOCATION;
    }

}
