
CREATE TABLE webdicom.dcmfile (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DCM_FILE_NAME VARCHAR(512) NOT NULL,
	PATIENT_BIRTH_DATE DATE NOT NULL,
	PATIENT_NAME VARCHAR(512) NOT NULL,
	STUDY_DATE DATE NOT NULL,
	CONSTRAINT primary_key PRIMARY KEY (ID),
	UNIQUE (DCM_FILE_NAME)
) 

