
package com.asutp.okocits3.ueh.ws.test;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataGate", targetNamespace = "http://ws.ueh.okocits3.asutp.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataGate {


    /**
     * 
     * @param taskName
     */
    @WebMethod
    @RequestWrapper(localName = "registerTask", targetNamespace = "http://ws.ueh.okocits3.asutp.com/", className = "com.asutp.okocits3.ueh.ws.test.RegisterTask")
    @ResponseWrapper(localName = "registerTaskResponse", targetNamespace = "http://ws.ueh.okocits3.asutp.com/", className = "com.asutp.okocits3.ueh.ws.test.RegisterTaskResponse")
    @Action(input = "http://ws.ueh.okocits3.asutp.com/DataGate/registerTaskRequest", output = "http://ws.ueh.okocits3.asutp.com/DataGate/registerTaskResponse")
    public void registerTask(
        @WebParam(name = "taskName", targetNamespace = "")
        String taskName);

    /**
     * 
     * @param dateEnd
     * @param dateBegin
     * @param parameters
     * @param outbound
     * @param taskName
     */
    @WebMethod
    @RequestWrapper(localName = "subscribe", targetNamespace = "http://ws.ueh.okocits3.asutp.com/", className = "com.asutp.okocits3.ueh.ws.test.Subscribe")
    @ResponseWrapper(localName = "subscribeResponse", targetNamespace = "http://ws.ueh.okocits3.asutp.com/", className = "com.asutp.okocits3.ueh.ws.test.SubscribeResponse")
    @Action(input = "http://ws.ueh.okocits3.asutp.com/DataGate/subscribeRequest", output = "http://ws.ueh.okocits3.asutp.com/DataGate/subscribeResponse")
    public void subscribe(
        @WebParam(name = "taskName", targetNamespace = "")
        String taskName,
        @WebParam(name = "dateBegin", targetNamespace = "")
        XMLGregorianCalendar dateBegin,
        @WebParam(name = "dateEnd", targetNamespace = "")
        XMLGregorianCalendar dateEnd,
        @WebParam(name = "outbound", targetNamespace = "")
        boolean outbound,
        @WebParam(name = "parameters", targetNamespace = "")
        List<SubscribeItem> parameters);

    /**
     * 
     * @param taskName
     */
    @WebMethod
    @RequestWrapper(localName = "confirm", targetNamespace = "http://ws.ueh.okocits3.asutp.com/", className = "com.asutp.okocits3.ueh.ws.test.Confirm")
    @ResponseWrapper(localName = "confirmResponse", targetNamespace = "http://ws.ueh.okocits3.asutp.com/", className = "com.asutp.okocits3.ueh.ws.test.ConfirmResponse")
    @Action(input = "http://ws.ueh.okocits3.asutp.com/DataGate/confirmRequest", output = "http://ws.ueh.okocits3.asutp.com/DataGate/confirmResponse")
    public void confirm(
        @WebParam(name = "taskName", targetNamespace = "")
        String taskName);

    /**
     * 
     * @param taskName
     * @return
     *     returns java.util.List<com.asutp.okocits3.ueh.ws.test.OkoParameter>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://ws.ueh.okocits3.asutp.com/", className = "com.asutp.okocits3.ueh.ws.test.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://ws.ueh.okocits3.asutp.com/", className = "com.asutp.okocits3.ueh.ws.test.GetDataResponse")
    @Action(input = "http://ws.ueh.okocits3.asutp.com/DataGate/getDataRequest", output = "http://ws.ueh.okocits3.asutp.com/DataGate/getDataResponse")
    public List<OkoParameter> getData(
        @WebParam(name = "taskName", targetNamespace = "")
        String taskName);

}
