
package org.psystems.dicom.webservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DicomService", targetNamespace = "http://webservice.dicom.psystems.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DicomService {


    /**
     * 
     * @param patient
     * @param directionLocation
     * @param directionId
     * @param senderLpu
     * @param servicesDirect
     * @param doctorDirect
     * @param device
     * @param diagnosisDirect
     * @param directionCode
     * @param dateTimePlanned
     * @param dateDirection
     * @param modality
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeDirection", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.MakeDirection")
    @ResponseWrapper(localName = "makeDirectionResponse", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.MakeDirectionResponse")
    public long makeDirection(
        @WebParam(name = "directionId", targetNamespace = "")
        String directionId,
        @WebParam(name = "modality", targetNamespace = "")
        String modality,
        @WebParam(name = "doctorDirect", targetNamespace = "")
        Employee doctorDirect,
        @WebParam(name = "diagnosisDirect", targetNamespace = "")
        List<Diagnosis> diagnosisDirect,
        @WebParam(name = "servicesDirect", targetNamespace = "")
        List<Service> servicesDirect,
        @WebParam(name = "dateDirection", targetNamespace = "")
        String dateDirection,
        @WebParam(name = "device", targetNamespace = "")
        ManufacturerDevice device,
        @WebParam(name = "dateTimePlanned", targetNamespace = "")
        String dateTimePlanned,
        @WebParam(name = "directionCode", targetNamespace = "")
        String directionCode,
        @WebParam(name = "directionLocation", targetNamespace = "")
        String directionLocation,
        @WebParam(name = "patient", targetNamespace = "")
        Patient patient,
        @WebParam(name = "senderLpu", targetNamespace = "")
        String senderLpu);

    /**
     * 
     * @param directionId
     * @return
     *     returns org.psystems.dicom.webservice.client.Direction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDirectionBydirectionId", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.GetDirectionBydirectionId")
    @ResponseWrapper(localName = "getDirectionBydirectionIdResponse", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.GetDirectionBydirectionIdResponse")
    public Direction getDirectionBydirectionId(
        @WebParam(name = "directionId", targetNamespace = "")
        String directionId);

    /**
     * 
     * @param id
     * @return
     *     returns org.psystems.dicom.webservice.client.Direction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDirectionById", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.GetDirectionById")
    @ResponseWrapper(localName = "getDirectionByIdResponse", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.GetDirectionByIdResponse")
    public Direction getDirectionById(
        @WebParam(name = "id", targetNamespace = "")
        long id);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.psystems.dicom.webservice.client.QueryStudyResp
     */
    @WebMethod
    @WebResult(name = "queryStudyResp", targetNamespace = "http://webservice.dicom.psystems.org", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public QueryStudyResp queryStudies(
        @WebParam(name = "queryStudyReq", targetNamespace = "http://webservice.dicom.psystems.org", partName = "parameters")
        QueryStudyReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.psystems.dicom.webservice.client.QueryDirectionResp
     */
    @WebMethod
    @WebResult(name = "queryDirectionResp", targetNamespace = "http://webservice.dicom.psystems.org", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public QueryDirectionResp queryDirections(
        @WebParam(name = "queryDirectionReq", targetNamespace = "http://webservice.dicom.psystems.org", partName = "parameters")
        QueryDirectionReq parameters);

}
