
package org.psystems.dicom.webservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DicomService", targetNamespace = "http://webservice.dicom.psystems.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DicomService {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeDirection", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.MakeDirection")
    @ResponseWrapper(localName = "makeDirectionResponse", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.MakeDirectionResponse")
    public long makeDirection(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Employee arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<Diagnosis> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<Service> arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        ManufacturerDevice arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        Patient arg9);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.psystems.dicom.webservice.client.Direction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDirectionBydirectionId", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.GetDirectionBydirectionId")
    @ResponseWrapper(localName = "getDirectionBydirectionIdResponse", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.GetDirectionBydirectionIdResponse")
    public Direction getDirectionBydirectionId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.psystems.dicom.webservice.client.Direction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDirectionById", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.GetDirectionById")
    @ResponseWrapper(localName = "getDirectionByIdResponse", targetNamespace = "http://webservice.dicom.psystems.org/", className = "org.psystems.dicom.webservice.client.GetDirectionByIdResponse")
    public Direction getDirectionById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.psystems.dicom.webservice.client.QueryDirectionResp
     */
    @WebMethod
    @WebResult(name = "queryDirectionResp", targetNamespace = "http://webservice.dicom.psystems.org", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public QueryDirectionResp queryDirection(
        @WebParam(name = "queryDirectionReq", targetNamespace = "http://webservice.dicom.psystems.org", partName = "parameters")
        QueryDirectionReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.psystems.dicom.webservice.client.QueryStudyResp
     */
    @WebMethod
    @WebResult(name = "queryStudyResp", targetNamespace = "http://webservice.dicom.psystems.org", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public QueryStudyResp queryStudy(
        @WebParam(name = "queryStudyReq", targetNamespace = "http://webservice.dicom.psystems.org", partName = "parameters")
        QueryStudyReq parameters);

}
