
package org.psystems.dicom.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DicomServiceService", targetNamespace = "http://webservice.dicom.psystems.org/", wsdlLocation = "http://localhost:8080/dicom-webservice/DicomService?wsdl")
public class DicomServiceService
    extends Service
{

    private final static URL DICOMSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.psystems.dicom.webservice.client.DicomServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.psystems.dicom.webservice.client.DicomServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/dicom-webservice/DicomService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dicom-webservice/DicomService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DICOMSERVICESERVICE_WSDL_LOCATION = url;
    }

    public DicomServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DicomServiceService() {
        super(DICOMSERVICESERVICE_WSDL_LOCATION, new QName("http://webservice.dicom.psystems.org/", "DicomServiceService"));
    }

    /**
     * 
     * @return
     *     returns DicomService
     */
    @WebEndpoint(name = "DicomServicePort")
    public DicomService getDicomServicePort() {
        return super.getPort(new QName("http://webservice.dicom.psystems.org/", "DicomServicePort"), DicomService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DicomService
     */
    @WebEndpoint(name = "DicomServicePort")
    public DicomService getDicomServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.dicom.psystems.org/", "DicomServicePort"), DicomService.class, features);
    }

}
