package dicomcl;

import java.io.File;

import org.dcm4che2.data.DicomObject;
import org.dcm4che2.data.Tag;

public class DicomHeader 
{
	private String[] tags = { "CommandGroupLength", "LengthToEndRET00000001",
			"AffectedSOPClassUID", "RequestedSOPClassUID",
			"RecognitionCodeRET00000010", "CommandField", "MessageID",
			"MessageIDBeingRespondedTo", "InitiatorRET", "ReceiverRET",
			"FindLocationRET", "MoveDestination", "Priority", "DataSetType",
			"NumberOfMatchesRET", "ResponseSequenceNumberRET", "Status",
			"OffendingElement", "ErrorComment", "ErrorID",
			"AffectedSOPInstanceUID", "RequestedSOPInstanceUID", "EventTypeID",
			"AttributeIdentifierList", "ActionTypeID",
			"NumberOfRemainingSuboperations", "NumberOfCompletedSuboperations",
			"NumberOfFailedSuboperations", "NumberOfWarningSuboperations",
			"MoveOriginatorApplicationEntityTitle", "MoveOriginatorMessageID",
			"DIALOGReceiverRET", "TerminalTypeRET", "MessageSetIDRET",
			"EndMessageIDRET", "DisplayFormatRET", "PagePositionIDRET",
			"TextFormatIDRET", "NorRevRET", "AddGrayScaleRET", "BordersRET",
			"CopiesRET", "MagnificationTypeRET", "EraseRET", "PrintRET",
			"OverlaysRET", "FileMetaInformationGroupLength",
			"FileMetaInformationVersion", "MediaStorageSOPClassUID",
			"MediaStorageSOPInstanceUID", "TransferSyntaxUID",
			"ImplementationClassUID", "ImplementationVersionName",
			"SourceApplicationEntityTitle", "PrivateInformationCreatorUID",
			"PrivateInformation", "FilesetID", "FilesetDescriptorFileID",
			"SpecificCharacterSetOfFilesetDescriptorFile",
			"OffsetOfTheFirstDirectoryRecordOfTheRootDirectoryEntity",
			"OffsetOfTheLastDirectoryRecordOfTheRootDirectoryEntity",
			"FilesetConsistencyFlag", "DirectoryRecordSequence",
			"OffsetOfTheNextDirectoryRecord", "RecordInuseFlag",
			"OffsetOfReferencedLowerLevelDirectoryEntity",
			"DirectoryRecordType", "PrivateRecordUID", "ReferencedFileID",
			"MRDRDirectoryRecordOffsetRET", "ReferencedSOPClassUIDInFile",
			"ReferencedSOPInstanceUIDInFile",
			"ReferencedTransferSyntaxUIDInFile",
			"ReferencedRelatedGeneralSOPClassUIDInFile",
			"NumberOfReferencesRET", "LengthToEndRET00080001",
			"SpecificCharacterSet", "ImageType", "RecognitionCodeRET00080010",
			"InstanceCreationDate", "InstanceCreationTime",
			"InstanceCreatorUID", "SOPClassUID", "SOPInstanceUID",
			"RelatedGeneralSOPClassUID", "OriginalSpecializedSOPClassUID",
			"StudyDate", "SeriesDate", "AcquisitionDate", "ContentDate",
			"OverlayDateRET", "CurveDateRET", "AcquisitionDateTime",
			"StudyTime", "SeriesTime", "AcquisitionTime", "ContentTime",
			"OverlayTimeRET", "CurveTimeRET", "DataSetTypeRET",
			"DataSetSubtypeRET", "NuclearMedicineSeriesTypeRET",
			"AccessionNumber", "IssuerOfAccessionNumberSequence",
			"QueryRetrieveLevel", "RetrieveAETitle", "InstanceAvailability",
			"FailedSOPInstanceUIDList", "Modality", "ModalitiesInStudy",
			"SOPClassesInStudy", "ConversionType", "PresentationIntentType",
			"Manufacturer", "InstitutionName", "InstitutionAddress",
			"InstitutionCodeSequence", "ReferringPhysicianName",
			"ReferringPhysicianAddress", "ReferringPhysicianTelephoneNumbers",
			"ReferringPhysicianIdentificationSequence", "CodeValue",
			"CodingSchemeDesignator", "CodingSchemeVersion", "CodeMeaning",
			"MappingResource", "ContextGroupVersion",
			"ContextGroupLocalVersion", "ContextGroupExtensionFlag",
			"CodingSchemeUID", "ContextGroupExtensionCreatorUID",
			"ContextIdentifier", "CodingSchemeIdentificationSequence",
			"CodingSchemeRegistry", "CodingSchemeExternalID",
			"CodingSchemeName", "CodingSchemeResponsibleOrganization",
			"TimezoneOffsetFromUTC", "NetworkIDRET", "StationName",
			"StudyDescription", "ProcedureCodeSequence", "SeriesDescription",
			"InstitutionalDepartmentName", "PhysiciansOfRecord",
			"PhysiciansOfRecordIdentificationSequence",
			"PerformingPhysicianName",
			"PerformingPhysicianIdentificationSequence",
			"NameOfPhysiciansReadingStudy",
			"PhysiciansReadingStudyIdentificationSequence", "OperatorName",
			"OperatorIdentificationSequence", "AdmittingDiagnosesDescription",
			"AdmittingDiagnosesCodeSequence", "ManufacturerModelName",
			"ReferencedResultsSequenceRET", "ReferencedStudySequence",
			"ReferencedPerformedProcedureStepSequence",
			"ReferencedSeriesSequence", "ReferencedPatientSequence",
			"ReferencedVisitSequence", "ReferencedOverlaySequenceRET",
			"ReferencedWaveformSequence", "ReferencedImageSequence",
			"ReferencedCurveSequenceRET", "ReferencedInstanceSequence",
			"ReferencedRealWorldValueMappingInstanceSequence",
			"ReferencedSOPClassUID", "ReferencedSOPInstanceUID",
			"SOPClassesSupported", "ReferencedFrameNumber", "TransactionUID",
			"FailureReason", "FailedSOPSequence", "ReferencedSOPSequence",
			"StudiesContainingOtherReferencedInstancesSequence",
			"RelatedSeriesSequence", "LossyImageCompressionRetiredRET",
			"DerivationDescription", "SourceImageSequence", "StageName",
			"StageNumber", "NumberOfStages", "ViewName", "ViewNumber",
			"NumberOfEventTimers", "NumberOfViewsInStage", "EventElapsedTimes",
			"EventTimerNames", "StartTrim", "StopTrim",
			"RecommendedDisplayFrameRate", "TransducerPositionRET",
			"TransducerOrientationRET", "AnatomicStructureRET",
			"AnatomicRegionSequence", "AnatomicRegionModifierSequence",
			"PrimaryAnatomicStructureSequence",
			"AnatomicStructureSpaceOrRegionSequence",
			"PrimaryAnatomicStructureModifierSequence",
			"TransducerPositionSequenceRET",
			"TransducerPositionModifierSequenceRET",
			"TransducerOrientationSequenceRET",
			"TransducerOrientationModifierSequenceRET",
			"AnatomicStructureSpaceOrRegionCodeSequenceTrialRET",
			"AnatomicPortalOfEntranceCodeSequenceTrialRET",
			"AnatomicApproachDirectionCodeSequenceTrialRET",
			"AnatomicPerspectiveDescriptionTrialRET",
			"AnatomicPerspectiveCodeSequenceTrialRET",
			"AnatomicLocationOfExaminingInstrumentDescriptionTrialRET",
			"AnatomicLocationOfExaminingInstrumentCodeSequenceTrialRET",
			"AnatomicStructureSpaceOrRegionModifierCodeSequenceTrialRET",
			"OnAxisBackgroundAnatomicStructureCodeSequenceTrialRET",
			"AlternateRepresentationSequence", "IrradiationEventUID",
			"IdentifyingCommentsRET", "FrameType",
			"ReferencedImageEvidenceSequence", "ReferencedRawDataSequence",
			"CreatorVersionUID", "DerivationImageSequence",
			"SourceImageEvidenceSequence", "PixelPresentation",
			"VolumetricProperties", "VolumeBasedCalculationTechnique",
			"ComplexImageComponent", "AcquisitionContrast",
			"DerivationCodeSequence",
			"ReferencedGrayscalePresentationStateSequence",
			"ReferencedOtherPlaneSequence", "FrameDisplaySequence",
			"RecommendedDisplayFrameRateInFloat", "SkipFrameRangeFlag",
			"PatientName", "PatientID", "IssuerOfPatientID", "TypeOfPatientID",
			"IssuerOfPatientIDQualifiersSequence", "PatientBirthDate",
			"PatientBirthTime", "PatientSex",
			"PatientInsurancePlanCodeSequence",
			"PatientPrimaryLanguageCodeSequence",
			"PatientPrimaryLanguageCodeModifierSequence", "OtherPatientIDs",
			"OtherPatientNames", "OtherPatientIDsSequence", "PatientBirthName",
			"PatientAge", "PatientSize", "PatientWeight", "PatientAddress",
			"InsurancePlanIdentificationRET", "PatientMotherBirthName",
			"MilitaryRank", "BranchOfService", "MedicalRecordLocator",
			"MedicalAlerts", "Allergies", "CountryOfResidence",
			"RegionOfResidence", "PatientTelephoneNumbers", "EthnicGroup",
			"Occupation", "SmokingStatus", "AdditionalPatientHistory",
			"PregnancyStatus", "LastMenstrualDate",
			"PatientReligiousPreference", "PatientSpeciesDescription",
			"PatientSpeciesCodeSequence", "PatientSexNeutered",
			"PatientBreedDescription", "PatientBreedCodeSequence",
			"BreedRegistrationSequence", "BreedRegistrationNumber",
			"BreedRegistryCodeSequence", "ResponsiblePerson",
			"ResponsiblePersonRole", "ResponsibleOrganization",
			"PatientComments", "ExaminedBodyThickness",
			"ClinicalTrialSponsorName", "ClinicalTrialProtocolID",
			"ClinicalTrialProtocolName", "ClinicalTrialSiteID",
			"ClinicalTrialSiteName", "ClinicalTrialSubjectID",
			"ClinicalTrialSubjectReadingID", "ClinicalTrialTimePointID",
			"ClinicalTrialTimePointDescription",
			"ClinicalTrialCoordinatingCenterName", "PatientIdentityRemoved",
			"DeidentificationMethod", "DeidentificationMethodCodeSequence",
			"ClinicalTrialSeriesID", "ClinicalTrialSeriesDescription",
			"ContrastBolusAgent", "ContrastBolusAgentSequence",
			"ContrastBolusAdministrationRouteSequence", "BodyPartExamined",
			"ScanningSequence", "SequenceVariant", "ScanOptions",
			"MRAcquisitionType", "SequenceName", "AngioFlag",
			"InterventionDrugInformationSequence", "InterventionDrugStopTime",
			"InterventionDrugDose", "InterventionDrugSequence",
			"AdditionalDrugSequence", "RadionuclideRET", "Radiopharmaceutical",
			"EnergyWindowCenterlineRET", "EnergyWindowTotalWidthRET",
			"InterventionDrugName", "InterventionDrugStartTime",
			"InterventionSequence", "TherapyTypeRET", "InterventionStatus",
			"TherapyDescriptionRET", "InterventionDescription", "CineRate",
			"SliceThickness", "KVP", "CountsAccumulated",
			"AcquisitionTerminationCondition", "EffectiveDuration",
			"AcquisitionStartCondition", "AcquisitionStartConditionData",
			"AcquisitionTerminationConditionData", "RepetitionTime",
			"EchoTime", "InversionTime", "NumberOfAverages",
			"ImagingFrequency", "ImagedNucleus", "EchoNumbers",
			"MagneticFieldStrength", "SpacingBetweenSlices",
			"NumberOfPhaseEncodingSteps", "DataCollectionDiameter",
			"EchoTrainLength", "PercentSampling", "PercentPhaseFieldOfView",
			"PixelBandwidth", "DeviceSerialNumber", "DeviceUID", "DeviceID",
			"PlateID", "GeneratorID", "GridID", "CassetteID", "GantryID",
			"SecondaryCaptureDeviceID", "HardcopyCreationDeviceIDRET",
			"DateOfSecondaryCapture", "TimeOfSecondaryCapture",
			"SecondaryCaptureDeviceManufacturers",
			"HardcopyDeviceManufacturerRET",
			"SecondaryCaptureDeviceManufacturerModelName",
			"SecondaryCaptureDeviceSoftwareVersions",
			"HardcopyDeviceSoftwareVersionRET",
			"HardcopyDeviceManufacturerModelNameRET", "SoftwareVersions",
			"VideoImageFormatAcquired", "DigitalImageFormatAcquired",
			"ProtocolName", "ContrastBolusRoute", "ContrastBolusVolume",
			"ContrastBolusStartTime", "ContrastBolusStopTime",
			"ContrastBolusTotalDose", "SyringeCounts", "ContrastFlowRate",
			"ContrastFlowDuration", "ContrastBolusIngredient",
			"ContrastBolusIngredientConcentration", "SpatialResolution",
			"TriggerTime", "TriggerSourceOrType", "NominalInterval",
			"FrameTime", "CardiacFramingType", "FrameTimeVector", "FrameDelay",
			"ImageTriggerDelay", "MultiplexGroupTimeOffset",
			"TriggerTimeOffset", "SynchronizationTrigger",
			"SynchronizationChannel", "TriggerSamplePosition",
			"RadiopharmaceuticalRoute", "RadiopharmaceuticalVolume",
			"RadiopharmaceuticalStartTime", "RadiopharmaceuticalStopTime",
			"RadionuclideTotalDose", "RadionuclideHalfLife",
			"RadionuclidePositronFraction",
			"RadiopharmaceuticalSpecificActivity",
			"RadiopharmaceuticalStartDateTime",
			"RadiopharmaceuticalStopDateTime", "BeatRejectionFlag",
			"LowRRValue", "HighRRValue", "IntervalsAcquired",
			"IntervalsRejected", "PVCRejection", "SkipBeats", "HeartRate",
			"CardiacNumberOfImages", "TriggerWindow", "ReconstructionDiameter",
			"DistanceSourceToDetector", "DistanceSourceToPatient",
			"EstimatedRadiographicMagnificationFactor", "GantryDetectorTilt",
			"GantryDetectorSlew", "TableHeight", "TableTraverse",
			"TableMotion", "TableVerticalIncrement", "TableLateralIncrement",
			"TableLongitudinalIncrement", "TableAngle", "TableType",
			"RotationDirection", "AngularPositionRET", "RadialPosition",
			"ScanArc", "AngularStep", "CenterOfRotationOffset",
			"RotationOffsetRET", "FieldOfViewShape", "FieldOfViewDimensions",
			"ExposureTime", "XRayTubeCurrent", "Exposure", "ExposureInUAs",
			"AveragePulseWidth", "RadiationSetting", "RectificationType",
			"RadiationMode", "ImageAndFluoroscopyAreaDoseProduct",
			"FilterType", "TypeOfFilters", "IntensifierSize",
			"ImagerPixelSpacing", "Grid", "GeneratorPower",
			"CollimatorgridName", "CollimatorType", "FocalDistance",
			"XFocusCenter", "YFocusCenter", "FocalSpots",
			"AnodeTargetMaterial", "BodyPartThickness", "CompressionForce",
			"DateOfLastCalibration", "TimeOfLastCalibration",
			"ConvolutionKernel", "UpperLowerPixelValuesRET",
			"ActualFrameDuration", "CountRate", "PreferredPlaybackSequencing",
			"ReceiveCoilName", "TransmitCoilName", "PlateType", "PhosphorType",
			"ScanVelocity", "WholeBodyTechnique", "ScanLength",
			"AcquisitionMatrix", "InplanePhaseEncodingDirection", "FlipAngle",
			"VariableFlipAngleFlag", "SAR", "dBdt",
			"AcquisitionDeviceProcessingDescription",
			"AcquisitionDeviceProcessingCode", "CassetteOrientation",
			"CassetteSize", "ExposuresOnPlate", "RelativeXRayExposure",
			"ColumnAngulation", "TomoLayerHeight", "TomoAngle", "TomoTime",
			"TomoType", "TomoClass", "NumberOfTomosynthesisSourceImages",
			"PositionerMotion", "PositionerType", "PositionerPrimaryAngle",
			"PositionerSecondaryAngle", "PositionerPrimaryAngleIncrement",
			"PositionerSecondaryAngleIncrement", "DetectorPrimaryAngle",
			"DetectorSecondaryAngle", "ShutterShape",
			"ShutterLeftVerticalEdge", "ShutterRightVerticalEdge",
			"ShutterUpperHorizontalEdge", "ShutterLowerHorizontalEdge",
			"CenterOfCircularShutter", "RadiusOfCircularShutter",
			"VerticesOfThePolygonalShutter", "ShutterPresentationValue",
			"ShutterOverlayGroup", "ShutterPresentationColorCIELabValue",
			"CollimatorShape", "CollimatorLeftVerticalEdge",
			"CollimatorRightVerticalEdge", "CollimatorUpperHorizontalEdge",
			"CollimatorLowerHorizontalEdge", "CenterOfCircularCollimator",
			"RadiusOfCircularCollimator", "VerticesOfThePolygonalCollimator",
			"AcquisitionTimeSynchronized", "TimeSource",
			"TimeDistributionProtocol", "NTPSourceAddress", "PageNumberVector",
			"FrameLabelVector", "FramePrimaryAngleVector",
			"FrameSecondaryAngleVector", "SliceLocationVector",
			"DisplayWindowLabelVector", "NominalScannedPixelSpacing",
			"DigitizingDeviceTransportDirection", "RotationOfScannedFilm",
			"IVUSAcquisition", "IVUSPullbackRate", "IVUSGatedRate",
			"IVUSPullbackStartFrameNumber", "IVUSPullbackStopFrameNumber",
			"LesionNumber", "AcquisitionCommentsRET", "OutputPower",
			"TransducerData", "FocusDepth", "ProcessingFunction",
			"PostprocessingFunctionRET", "MechanicalIndex", "BoneThermalIndex",
			"CranialThermalIndex", "SoftTissueThermalIndex",
			"SoftTissuefocusThermalIndex", "SoftTissuesurfaceThermalIndex",
			"DynamicRangeRET", "TotalGainRET", "DepthOfScanField",
			"PatientPosition", "ViewPosition",
			"ProjectionEponymousNameCodeSequence",
			"ImageTransformationMatrixRET", "ImageTranslationVectorRET",
			"Sensitivity", "SequenceOfUltrasoundRegions",
			"RegionSpatialFormat", "RegionDataType", "RegionFlags",
			"RegionLocationMinX0", "RegionLocationMinY0",
			"RegionLocationMaxX1", "RegionLocationMaxY1", "ReferencePixelX0",
			"ReferencePixelY0", "PhysicalUnitsXDirection",
			"PhysicalUnitsYDirection", "ReferencePixelPhysicalValueX",
			"ReferencePixelPhysicalValueY", "PhysicalDeltaX", "PhysicalDeltaY",
			"TransducerFrequency", "TransducerType",
			"PulseRepetitionFrequency", "DopplerCorrectionAngle",
			"SteeringAngle", "DopplerSampleVolumeXPositionRetiredRET",
			"DopplerSampleVolumeXPosition",
			"DopplerSampleVolumeYPositionRetiredRET",
			"DopplerSampleVolumeYPosition", "TMLinePositionX0RetiredRET",
			"TMLinePositionX0", "TMLinePositionY0RetiredRET",
			"TMLinePositionY0", "TMLinePositionX1RetiredRET",
			"TMLinePositionX1", "TMLinePositionY1RetiredRET",
			"TMLinePositionY1", "PixelComponentOrganization",
			"PixelComponentMask", "PixelComponentRangeStart",
			"PixelComponentRangeStop", "PixelComponentPhysicalUnits",
			"PixelComponentDataType", "NumberOfTableBreakPoints",
			"TableOfXBreakPoints", "TableOfYBreakPoints",
			"NumberOfTableEntries", "TableOfPixelValues",
			"TableOfParameterValues", "RWaveTimeVector",
			"DetectorConditionsNominalFlag", "DetectorTemperature",
			"DetectorType", "DetectorConfiguration", "DetectorDescription",
			"DetectorMode", "DetectorID", "DateOfLastDetectorCalibration",
			"TimeOfLastDetectorCalibration",
			"ExposuresOnDetectorSinceLastCalibration",
			"ExposuresOnDetectorSinceManufactured",
			"DetectorTimeSinceLastExposure", "DetectorActiveTime",
			"DetectorActivationOffsetFromExposure", "DetectorBinning",
			"DetectorElementPhysicalSize", "DetectorElementSpacing",
			"DetectorActiveShape", "DetectorActiveDimensions",
			"DetectorActiveOrigin", "DetectorManufacturerName",
			"DetectorManufacturerModelName", "FieldOfViewOrigin",
			"FieldOfViewRotation", "FieldOfViewHorizontalFlip",
			"GridAbsorbingMaterial", "GridSpacingMaterial", "GridThickness",
			"GridPitch", "GridAspectRatio", "GridPeriod", "GridFocalDistance",
			"FilterMaterial", "FilterThicknessMinimum",
			"FilterThicknessMaximum", "ExposureControlMode",
			"ExposureControlModeDescription", "ExposureStatus",
			"PhototimerSetting", "ExposureTimeInUS", "XRayTubeCurrentInUA",
			"ContentQualification", "PulseSequenceName",
			"MRImagingModifierSequence", "EchoPulseSequence",
			"InversionRecovery", "FlowCompensation", "MultipleSpinEcho",
			"MultiplanarExcitation", "PhaseContrast", "TimeOfFlightContrast",
			"Spoiling", "SteadyStatePulseSequence", "EchoPlanarPulseSequence",
			"TagAngleFirstAxis", "MagnetizationTransfer", "T2Preparation",
			"BloodSignalNulling", "SaturationRecovery",
			"SpectrallySelectedSuppression", "SpectrallySelectedExcitation",
			"SpatialPresaturation", "Tagging", "OversamplingPhase",
			"TagSpacingFirstDimension", "GeometryOfKSpaceTraversal",
			"SegmentedKSpaceTraversal", "RectilinearPhaseEncodeReordering",
			"TagThickness", "PartialFourierDirection",
			"CardiacSynchronizationTechnique", "ReceiveCoilManufacturerName",
			"MRReceiveCoilSequence", "ReceiveCoilType",
			"QuadratureReceiveCoil", "MultiCoilDefinitionSequence",
			"MultiCoilConfiguration", "MultiCoilElementName",
			"MultiCoilElementUsed", "MRTransmitCoilSequence",
			"TransmitCoilManufacturerName", "TransmitCoilType",
			"SpectralWidth", "ChemicalShiftReference",
			"VolumeLocalizationTechnique",
			"MRAcquisitionFrequencyEncodingSteps", "Decoupling",
			"DecoupledNucleus", "DecouplingFrequency", "DecouplingMethod",
			"DecouplingChemicalShiftReference", "kspaceFiltering",
			"TimeDomainFiltering", "NumberOfZeroFills", "BaselineCorrection",
			"ParallelReductionFactorInplane", "CardiacRRIntervalSpecified",
			"AcquisitionDuration", "FrameAcquisitionDateTime",
			"DiffusionDirectionality", "DiffusionGradientDirectionSequence",
			"ParallelAcquisition", "ParallelAcquisitionTechnique",
			"InversionTimes", "MetaboliteMapDescription", "PartialFourier",
			"EffectiveEchoTime", "MetaboliteMapCodeSequence",
			"ChemicalShiftSequence", "CardiacSignalSource", "DiffusionBvalue",
			"DiffusionGradientOrientation", "VelocityEncodingDirection",
			"VelocityEncodingMinimumValue", "NumberOfKSpaceTrajectories",
			"CoverageOfKSpace", "SpectroscopyAcquisitionPhaseRows",
			"ParallelReductionFactorInplaneRetiredRET", "TransmitterFrequency",
			"ResonantNucleus", "FrequencyCorrection",
			"MRSpectroscopyFOVGeometrySequence", "SlabThickness",
			"SlabOrientation", "MidSlabPosition",
			"MRSpatialSaturationSequence",
			"MRTimingAndRelatedParametersSequence", "MREchoSequence",
			"MRModifierSequence", "MRDiffusionSequence",
			"CardiacSynchronizationSequence", "MRAveragesSequence",
			"MRFOVGeometrySequence", "VolumeLocalizationSequence",
			"SpectroscopyAcquisitionDataColumns", "DiffusionAnisotropyType",
			"FrameReferenceDateTime", "MRMetaboliteMapSequence",
			"ParallelReductionFactorOutofplane",
			"SpectroscopyAcquisitionOutofplanePhaseSteps",
			"BulkMotionStatusRET", "ParallelReductionFactorSecondInplane",
			"CardiacBeatRejectionTechnique",
			"RespiratoryMotionCompensationTechnique",
			"RespiratorySignalSource", "BulkMotionCompensationTechnique",
			"BulkMotionSignalSource", "ApplicableSafetyStandardAgency",
			"ApplicableSafetyStandardDescription", "OperatingModeSequence",
			"OperatingModeType", "OperatingMode",
			"SpecificAbsorptionRateDefinition", "GradientOutputType",
			"SpecificAbsorptionRateValue", "GradientOutput",
			"FlowCompensationDirection", "TaggingDelay",
			"RespiratoryMotionCompensationTechniqueDescription",
			"RespiratorySignalSourceID",
			"ChemicalShiftsMinimumIntegrationLimitInHzRET",
			"ChemicalShiftsMaximumIntegrationLimitInHzRET",
			"MRVelocityEncodingSequence", "FirstOrderPhaseCorrection",
			"WaterReferencedPhaseCorrection", "MRSpectroscopyAcquisitionType",
			"RespiratoryCyclePosition", "VelocityEncodingMaximumValue",
			"TagSpacingSecondDimension", "TagAngleSecondAxis",
			"FrameAcquisitionDuration", "MRImageFrameTypeSequence",
			"MRSpectroscopyFrameTypeSequence",
			"MRAcquisitionPhaseEncodingStepsInplane",
			"MRAcquisitionPhaseEncodingStepsOutofplane",
			"SpectroscopyAcquisitionPhaseColumns", "CardiacCyclePosition",
			"SpecificAbsorptionRateSequence", "RFEchoTrainLength",
			"GradientEchoTrainLength",
			"ChemicalShiftsMinimumIntegrationLimitInPpm",
			"ChemicalShiftsMaximumIntegrationLimitInPpm",
			"CTAcquisitionTypeSequence", "AcquisitionType", "TubeAngle",
			"CTAcquisitionDetailsSequence", "RevolutionTime",
			"SingleCollimationWidth", "TotalCollimationWidth",
			"CTTableDynamicsSequence", "TableSpeed", "TableFeedPerRotation",
			"SpiralPitchFactor", "CTGeometrySequence",
			"DataCollectionCenterPatient", "CTReconstructionSequence",
			"ReconstructionAlgorithm", "ConvolutionKernelGroup",
			"ReconstructionFieldOfView", "ReconstructionTargetCenterPatient",
			"ReconstructionAngle", "ImageFilter", "CTExposureSequence",
			"ReconstructionPixelSpacing", "ExposureModulationType",
			"EstimatedDoseSaving", "CTXRayDetailsSequence",
			"CTPositionSequence", "TablePosition", "ExposureTimeInMs",
			"CTImageFrameTypeSequence", "XRayTubeCurrentInMA", "ExposureInMAs",
			"ConstantVolumeFlag", "FluoroscopyFlag",
			"DistanceSourceToDataCollectionCenter", "ContrastBolusAgentNumber",
			"ContrastBolusIngredientCodeSequence",
			"ContrastAdministrationProfileSequence",
			"ContrastBolusUsageSequence", "ContrastBolusAgentAdministered",
			"ContrastBolusAgentDetected", "ContrastBolusAgentPhase", "CTDIvol",
			"CTDIPhantomTypeCodeSequence", "CalciumScoringMassFactorPatient",
			"CalciumScoringMassFactorDevice", "CTAdditionalXRaySourceSequence",
			"ProjectionPixelCalibrationSequence", "DistanceSourceToIsocenter",
			"DistanceObjectToTableTop", "ObjectPixelSpacingInCenterOfBeam",
			"PositionerPositionSequence", "TablePositionSequence",
			"CollimatorShapeSequence", "XAXRFFrameCharacteristicsSequence",
			"FrameAcquisitionSequence", "XRayReceptorType",
			"AcquisitionProtocolName", "AcquisitionProtocolDescription",
			"ContrastBolusIngredientOpaque",
			"DistanceReceptorPlaneToDetectorHousing", "IntensifierActiveShape",
			"IntensifierActiveDimensions", "PhysicalDetectorSize",
			"PositionOfIsocenterProjection", "FieldOfViewSequence",
			"FieldOfViewDescription", "ExposureControlSensingRegionsSequence",
			"ExposureControlSensingRegionShape",
			"ExposureControlSensingRegionLeftVerticalEdge",
			"ExposureControlSensingRegionRightVerticalEdge",
			"ExposureControlSensingRegionUpperHorizontalEdge",
			"ExposureControlSensingRegionLowerHorizontalEdge",
			"CenterOfCircularExposureControlSensingRegion",
			"RadiusOfCircularExposureControlSensingRegion",
			"VerticesOfThePolygonalExposureControlSensingRegion",
			"ColumnAngulationPatient", "BeamAngle",
			"FrameDetectorParametersSequence", "CalculatedAnatomyThickness",
			"CalibrationSequence", "ObjectThicknessSequence",
			"PlaneIdentification", "FieldOfViewDimensionsInFloat",
			"IsocenterReferenceSystemSequence",
			"PositionerIsocenterPrimaryAngle",
			"PositionerIsocenterSecondaryAngle",
			"PositionerIsocenterDetectorRotationAngle",
			"TableXPositionToIsocenter", "TableYPositionToIsocenter",
			"TableZPositionToIsocenter", "TableHorizontalRotationAngle",
			"TableHeadTiltAngle", "TableCradleTiltAngle",
			"FrameDisplayShutterSequence", "AcquiredImageAreaDoseProduct",
			"CarmPositionerTabletopRelationship", "XRayGeometrySequence",
			"IrradiationEventIdentificationSequence",
			"XRay3DFrameTypeSequence", "ContributingSourcesSequence",
			"XRay3DAcquisitionSequence", "PrimaryPositionerScanArc",
			"SecondaryPositionerScanArc", "PrimaryPositionerScanStartAngle",
			"SecondaryPositionerScanStartAngle", "PrimaryPositionerIncrement",
			"SecondaryPositionerIncrement", "StartAcquisitionDateTime",
			"EndAcquisitionDateTime", "ApplicationName", "ApplicationVersion",
			"ApplicationManufacturer", "AlgorithmType", "AlgorithmDescription",
			"XRay3DReconstructionSequence", "ReconstructionDescription",
			"PerProjectionAcquisitionSequence", "DiffusionBmatrixSequence",
			"DiffusionBvalueXX", "DiffusionBvalueXY", "DiffusionBvalueXZ",
			"DiffusionBvalueYY", "DiffusionBvalueYZ", "DiffusionBvalueZZ",
			"DecayCorrectionDateTime", "StartDensityThreshold",
			"StartRelativeDensityDifferenceThreshold",
			"StartCardiacTriggerCountThreshold",
			"StartRespiratoryTriggerCountThreshold",
			"TerminationCountsThreshold", "TerminationDensityThreshold",
			"TerminationRelativeDensityThreshold", "TerminationTimeThreshold",
			"TerminationCardiacTriggerCountThreshold",
			"TerminationRespiratoryTriggerCountThreshold", "DetectorGeometry",
			"TransverseDetectorSeparation", "AxialDetectorDimension",
			"RadiopharmaceuticalAgentNumber", "PETFrameAcquisitionSequence",
			"PETDetectorMotionDetailsSequence", "PETTableDynamicsSequence",
			"PETPositionSequence", "PETFrameCorrectionFactorsSequence",
			"RadiopharmaceuticalUsageSequence", "AttenuationCorrectionSource",
			"NumberOfIterations", "NumberOfSubsets",
			"PETReconstructionSequence", "PETFrameTypeSequence",
			"TimeOfFlightInformationUsed", "ReconstructionType", "DynamicFlag",
			"IterativeReconstructionMethod",
			"AttenuationCorrectionTemporalRelationship",
			"PatientPhysiologicalStateSequence",
			"PatientPhysiologicalStateCodeSequence",
			"ContributingEquipmentSequence", "ContributionDateTime",
			"ContributionDescription", "StudyInstanceUID", "SeriesInstanceUID",
			"StudyID", "SeriesNumber", "AcquisitionNumber", "InstanceNumber",
			"IsotopeNumberRET", "PhaseNumberRET", "IntervalNumberRET",
			"TimeSlotNumberRET", "AngleNumberRET", "ItemNumber",
			"PatientOrientation", "OverlayNumberRET", "CurveNumberRET",
			"LookupTableNumberRET", "ImagePositionRET", "ImagePositionPatient",
			"ImageOrientationRET", "ImageOrientationPatient", "LocationRET",
			"FrameOfReferenceUID", "Laterality", "ImageLaterality",
			"ImageGeometryTypeRET", "MaskingImageRET",
			"TemporalPositionIdentifier", "NumberOfTemporalPositions",
			"TemporalResolution", "SynchronizationFrameOfReferenceUID",
			"SeriesInStudyRET", "AcquisitionsInSeriesRET",
			"ImagesInAcquisition", "ImagesInSeriesRET",
			"AcquisitionsInStudyRET", "ImagesInStudyRET", "ReferenceRET",
			"PositionReferenceIndicator", "SliceLocation",
			"OtherStudyNumbersRET", "NumberOfPatientRelatedStudies",
			"NumberOfPatientRelatedSeries", "NumberOfPatientRelatedInstances",
			"NumberOfStudyRelatedSeries", "NumberOfStudyRelatedInstances",
			"NumberOfSeriesRelatedInstances", "SourceImageIDsRET",
			"ModifyingDeviceIDRET", "ModifiedImageIDRET",
			"ModifiedImageDateRET", "ModifyingDeviceManufacturerRET",
			"ModifiedImageTimeRET", "ModifiedImageDescriptionRET",
			"ImageComments", "OriginalImageIdentificationRET",
			"OriginalImageIdentificationNomenclatureRET", "StackID",
			"InStackPositionNumber", "FrameAnatomySequence", "FrameLaterality",
			"FrameContentSequence", "PlanePositionSequence",
			"PlaneOrientationSequence", "TemporalPositionIndex",
			"NominalCardiacTriggerDelayTime", "FrameAcquisitionNumber",
			"DimensionIndexValues", "FrameComments", "ConcatenationUID",
			"InconcatenationNumber", "InconcatenationTotalNumber",
			"DimensionOrganizationUID", "DimensionIndexPointer",
			"FunctionalGroupPointer", "DimensionIndexPrivateCreator",
			"DimensionOrganizationSequence", "DimensionIndexSequence",
			"ConcatenationFrameOffsetNumber", "FunctionalGroupPrivateCreator",
			"NominalPercentageOfCardiacPhase",
			"NominalPercentageOfRespiratoryPhase",
			"StartingRespiratoryAmplitude", "StartingRespiratoryPhase",
			"EndingRespiratoryAmplitude", "EndingRespiratoryPhase",
			"RespiratoryTriggerType", "RRIntervalTimeNominal",
			"ActualCardiacTriggerDelayTime",
			"RespiratorySynchronizationSequence", "RespiratoryIntervalTime",
			"NominalRespiratoryTriggerDelayTime",
			"RespiratoryTriggerDelayThreshold",
			"ActualRespiratoryTriggerDelayTime", "DimensionDescriptionLabel",
			"PatientOrientationInFrameSequence", "FrameLabel",
			"AcquisitionIndex", "ContributingSOPInstancesReferenceSequence",
			"ReconstructionIndex", "LightPathFilterPassThroughWavelength",
			"LightPathFilterPassBand", "ImagePathFilterPassThroughWavelength",
			"ImagePathFilterPassBand", "PatientEyeMovementCommanded",
			"PatientEyeMovementCommandCodeSequence", "SphericalLensPower",
			"CylinderLensPower", "CylinderAxis", "EmmetropicMagnification",
			"IntraOcularPressure", "HorizontalFieldOfView", "PupilDilated",
			"DegreeOfDilation", "StereoBaselineAngle",
			"StereoBaselineDisplacement", "StereoHorizontalPixelOffset",
			"StereoVerticalPixelOffset", "StereoRotation",
			"AcquisitionDeviceTypeCodeSequence",
			"IlluminationTypeCodeSequence",
			"LightPathFilterTypeStackCodeSequence",
			"ImagePathFilterTypeStackCodeSequence", "LensesCodeSequence",
			"ChannelDescriptionCodeSequence", "RefractiveStateSequence",
			"MydriaticAgentCodeSequence", "RelativeImagePositionCodeSequence",
			"StereoPairsSequence", "LeftImageSequence", "RightImageSequence",
			"AxialLengthOfTheEye", "OphthalmicFrameLocationSequence",
			"ReferenceCoordinates", "DepthSpatialResolution",
			"MaximumDepthDistortion", "AlongscanSpatialResolution",
			"MaximumAlongscanDistortion", "OphthalmicImageOrientation",
			"DepthOfTransverseImage",
			"MydriaticAgentConcentrationUnitsSequence",
			"AcrossscanSpatialResolution", "MaximumAcrossscanDistortion",
			"MydriaticAgentConcentration", "IlluminationWaveLength",
			"IlluminationPower", "IlluminationBandwidth",
			"MydriaticAgentSequence", "SamplesPerPixel", "SamplesPerPixelUsed",
			"PhotometricInterpretation", "ImageDimensionsRET",
			"PlanarConfiguration", "NumberOfFrames", "FrameIncrementPointer",
			"FrameDimensionPointer", "Rows", "Columns", "PlanesRET",
			"UltrasoundColorDataPresent", "PixelSpacing", "ZoomFactor",
			"ZoomCenter", "PixelAspectRatio", "ImageFormatRET",
			"ManipulatedImageRET", "CorrectedImage",
			"CompressionRecognitionCodeRET", "CompressionCodeRET",
			"CompressionOriginatorRET", "CompressionLabelRET",
			"CompressionDescriptionRET", "CompressionSequenceRET",
			"CompressionStepPointersRET", "RepeatIntervalRET",
			"BitsGroupedRET", "PerimeterTableRET", "PerimeterValueRET",
			"PredictorRowsRET", "PredictorColumnsRET", "PredictorConstantsRET",
			"BlockedPixelsRET", "BlockRowsRET", "BlockColumnsRET",
			"RowOverlapRET", "ColumnOverlapRET", "BitsAllocated", "BitsStored",
			"HighBit", "PixelRepresentation", "SmallestValidPixelValueRET",
			"LargestValidPixelValueRET", "SmallestImagePixelValue",
			"LargestImagePixelValue", "SmallestPixelValueInSeries",
			"LargestPixelValueInSeries", "SmallestImagePixelValueInPlaneRET",
			"LargestImagePixelValueInPlaneRET", "PixelPaddingValue",
			"PixelPaddingRangeLimit", "ImageLocationRET",
			"QualityControlImage", "BurnedInAnnotation", "TransformLabelRET",
			"TransformVersionNumberRET", "NumberOfTransformStepsRET",
			"SequenceOfCompressedDataRET", "DetailsOfCoefficientsRET",
			"RowsForNthOrderCoefficientsRET",
			"ColumnsForNthOrderCoefficientsRET", "CoefficientCodingRET",
			"CoefficientCodingPointersRET", "DCTLabelRET",
			"DataBlockDescriptionRET", "DataBlockRET",
			"NormalizationFactorFormatRET", "ZonalMapNumberFormatRET",
			"ZonalMapLocationRET", "ZonalMapFormatRET", "AdaptiveMapFormatRET",
			"CodeNumberFormatRET", "CodeLabelRET", "NumberOfTableRET",
			"CodeTableLocationRET", "BitsForCodeWordRET",
			"ImageDataLocationRET", "PixelSpacingCalibrationType",
			"PixelSpacingCalibrationDescription", "PixelIntensityRelationship",
			"PixelIntensityRelationshipSign", "WindowCenter", "WindowWidth",
			"RescaleIntercept", "RescaleSlope", "RescaleType",
			"WindowCenterWidthExplanation", "VOILUTFunction", "GrayScaleRET",
			"RecommendedViewingMode", "GrayLookupTableDescriptorRET",
			"RedPaletteColorLookupTableDescriptor",
			"GreenPaletteColorLookupTableDescriptor",
			"BluePaletteColorLookupTableDescriptor",
			"LargeRedPaletteColorLookupTableDescriptorRET",
			"LargeGreenPaletteColorLookupTableDescriptorRET",
			"LargeBluePaletteColorLookupTableDescriptorRET",
			"PaletteColorLookupTableUID", "GrayLookupTableDataRET",
			"RedPaletteColorLookupTableData",
			"GreenPaletteColorLookupTableData",
			"BluePaletteColorLookupTableData",
			"LargeRedPaletteColorLookupTableDataRET",
			"LargeGreenPaletteColorLookupTableDataRET",
			"LargeBluePaletteColorLookupTableDataRET",
			"LargePaletteColorLookupTableUIDRET",
			"SegmentedRedPaletteColorLookupTableData",
			"SegmentedGreenPaletteColorLookupTableData",
			"SegmentedBluePaletteColorLookupTableData", "ImplantPresent",
			"PartialView", "PartialViewDescription", "PartialViewCodeSequence",
			"SpatialLocationsPreserved", "ICCProfile", "LossyImageCompression",
			"LossyImageCompressionRatio", "LossyImageCompressionMethod",
			"ModalityLUTSequence", "LUTDescriptor", "LUTExplanation",
			"ModalityLUTType", "LUTData", "VOILUTSequence",
			"SoftcopyVOILUTSequence", "ImagePresentationCommentsRET",
			"BiPlaneAcquisitionSequenceRET", "RepresentativeFrameNumber",
			"FrameNumbersOfInterestFOI", "FramesOfInterestDescription",
			"FrameOfInterestType", "MaskPointersRET", "RWavePointer",
			"MaskSubtractionSequence", "MaskOperation", "ApplicableFrameRange",
			"MaskFrameNumbers", "ContrastFrameAveraging", "MaskSubpixelShift",
			"TIDOffset", "MaskOperationExplanation", "PixelDataProviderURL",
			"DataPointRows", "DataPointColumns", "SignalDomainColumns",
			"LargestMonochromePixelValueRET", "DataRepresentation",
			"PixelMeasuresSequence", "FrameVOILUTSequence",
			"PixelValueTransformationSequence", "SignalDomainRows",
			"DisplayFilterPercentage", "FramePixelShiftSequence",
			"SubtractionItemID", "PixelIntensityRelationshipLUTSequence",
			"FramePixelDataPropertiesSequence", "GeometricalProperties",
			"GeometricMaximumDistortion", "ImageProcessingApplied",
			"MaskSelectionMode", "LUTFunction",
			"ImageToEquipmentMappingMatrix",
			"EquipmentCoordinateSystemIdentification", "DecayCorrected",
			"AttenuationCorrected", "ScatterCorrected", "DeadTimeCorrected",
			"GantryMotionCorrected", "PatientMotionCorrected",
			"CountLossNormalizationCorrected", "RandomsCorrected",
			"NonuniformRadialSamplingCorrected", "SensitivityCalibrated",
			"DetectorNormalizationCorrection", "StudyStatusIDRET",
			"StudyPriorityIDRET", "StudyIDIssuerRET", "StudyVerifiedDateRET",
			"StudyVerifiedTimeRET", "StudyReadDateRET", "StudyReadTimeRET",
			"ScheduledStudyStartDateRET", "ScheduledStudyStartTimeRET",
			"ScheduledStudyStopDateRET", "ScheduledStudyStopTimeRET",
			"ScheduledStudyLocationRET", "ScheduledStudyLocationAETitleRET",
			"ReasonForStudyRET", "RequestingPhysicianIdentificationSequence",
			"RequestingPhysician", "RequestingService", "StudyArrivalDateRET",
			"StudyArrivalTimeRET", "StudyCompletionDateRET",
			"StudyCompletionTimeRET", "StudyComponentStatusIDRET",
			"RequestedProcedureDescription", "RequestedProcedureCodeSequence",
			"RequestedContrastAgent", "StudyCommentsRET",
			"ReferencedPatientAliasSequence", "VisitStatusID", "AdmissionID",
			"IssuerOfAdmissionIDRET", "IssuerOfAdmissionIDSequence",
			"RouteOfAdmissions", "ScheduledAdmissionDateRET",
			"ScheduledAdmissionTimeRET", "ScheduledDischargeDateRET",
			"ScheduledDischargeTimeRET",
			"ScheduledPatientInstitutionResidenceRET", "AdmittingDate",
			"AdmittingTime", "DischargeDateRET", "DischargeTimeRET",
			"DischargeDiagnosisDescriptionRET",
			"DischargeDiagnosisCodeSequenceRET", "SpecialNeeds",
			"ServiceEpisodeID", "IssuerOfServiceEpisodeIDRET",
			"ServiceEpisodeDescription", "IssuerOfServiceEpisodeIDSequence",
			"PertinentDocumentsSequence", "CurrentPatientLocation",
			"PatientInstitutionResidence", "PatientState",
			"PatientClinicalTrialParticipationSequence", "VisitComments",
			"WaveformOriginality", "NumberOfWaveformChannels",
			"NumberOfWaveformSamples", "SamplingFrequency",
			"MultiplexGroupLabel", "ChannelDefinitionSequence",
			"WaveformChannelNumber", "ChannelLabel", "ChannelStatus",
			"ChannelSourceSequence", "ChannelSourceModifiersSequence",
			"SourceWaveformSequence", "ChannelDerivationDescription",
			"ChannelSensitivity", "ChannelSensitivityUnitsSequence",
			"ChannelSensitivityCorrectionFactor", "ChannelBaseline",
			"ChannelTimeSkew", "ChannelSampleSkew", "ChannelOffset",
			"WaveformBitsStored", "FilterLowFrequency", "FilterHighFrequency",
			"NotchFilterFrequency", "NotchFilterBandwidth",
			"WaveformDataDisplayScale", "WaveformDisplayBackgroundCIELabValue",
			"WaveformPresentationGroupSequence", "PresentationGroupNumber",
			"ChannelDisplaySequence", "ChannelRecommendedDisplayCIELabValue",
			"ChannelPosition", "DisplayShadingFlag",
			"FractionalChannelDisplayScale", "AbsoluteChannelDisplayScale",
			"MultiplexedAudioChannelsDescriptionCodeSequence",
			"ChannelIdentificationCode", "ChannelMode",
			"ScheduledStationAETitle", "ScheduledProcedureStepStartDate",
			"ScheduledProcedureStepStartTime", "ScheduledProcedureStepEndDate",
			"ScheduledProcedureStepEndTime",
			"ScheduledPerformingPhysicianName",
			"ScheduledProcedureStepDescription",
			"ScheduledProtocolCodeSequence", "ScheduledProcedureStepID",
			"StageCodeSequence",
			"ScheduledPerformingPhysicianIdentificationSequence",
			"ScheduledStationName", "ScheduledProcedureStepLocation",
			"PreMedication", "ScheduledProcedureStepStatus",
			"OrderPlacerIdentifierSequence", "OrderFillerIdentifierSequence",
			"LocalNamespaceEntityID", "UniversalEntityID",
			"UniversalEntityIDType", "IdentifierTypeCode",
			"AssigningFacilitySequence", "AssigningJurisdictionCodeSequence",
			"AssigningAgencyOrDepartmentCodeSequence",
			"ScheduledProcedureStepSequence",
			"ReferencedNonImageCompositeSOPInstanceSequence",
			"PerformedStationAETitle", "PerformedStationName",
			"PerformedLocation", "PerformedProcedureStepStartDate",
			"PerformedProcedureStepStartTime", "PerformedProcedureStepEndDate",
			"PerformedProcedureStepEndTime", "PerformedProcedureStepStatus",
			"PerformedProcedureStepID", "PerformedProcedureStepDescription",
			"PerformedProcedureTypeDescription",
			"PerformedProtocolCodeSequence", "ScheduledStepAttributesSequence",
			"RequestAttributesSequence", "CommentsOnThePerformedProcedureStep",
			"PerformedProcedureStepDiscontinuationReasonCodeSequence",
			"QuantitySequence", "Quantity", "MeasuringUnitsSequence",
			"BillingItemSequence", "TotalTimeOfFluoroscopy",
			"TotalNumberOfExposures", "EntranceDose", "ExposedArea",
			"DistanceSourceToEntrance", "DistanceSourceToSupportRET",
			"ExposureDoseSequence", "CommentsOnRadiationDose", "XRayOutput",
			"HalfValueLayer", "OrganDose", "OrganExposed",
			"BillingProcedureStepSequence", "FilmConsumptionSequence",
			"BillingSuppliesAndDevicesSequence",
			"ReferencedProcedureStepSequenceRET", "PerformedSeriesSequence",
			"CommentsOnTheScheduledProcedureStep", "ProtocolContextSequence",
			"ContentItemModifierSequence", "SpecimenAccessionNumber",
			"SpecimenSequence", "SpecimenIdentifier",
			"SpecimenDescriptionSequenceTrialRET",
			"SpecimenDescriptionTrialRET", "AcquisitionContextSequence",
			"AcquisitionContextDescription", "SpecimenTypeCodeSequence",
			"SlideIdentifier", "ImageCenterPointCoordinatesSequence",
			"XOffsetInSlideCoordinateSystem", "YOffsetInSlideCoordinateSystem",
			"ZOffsetInSlideCoordinateSystem", "PixelSpacingSequence",
			"CoordinateSystemAxisCodeSequence", "MeasurementUnitsCodeSequence",
			"VitalStainCodeSequenceTrialRET", "RequestedProcedureID",
			"ReasonForTheRequestedProcedure", "RequestedProcedurePriority",
			"PatientTransportArrangements", "RequestedProcedureLocation",
			"PlacerOrderNumberProcedureRET", "FillerOrderNumberProcedureRET",
			"ConfidentialityCode", "ReportingPriority",
			"ReasonForRequestedProcedureCodeSequence",
			"NamesOfIntendedRecipientsOfResults",
			"IntendedRecipientsOfResultsIdentificationSequence",
			"PersonIdentificationCodeSequence", "PersonAddress",
			"PersonTelephoneNumbers", "RequestedProcedureComments",
			"ReasonForTheImagingServiceRequestRET",
			"IssueDateOfImagingServiceRequest",
			"IssueTimeOfImagingServiceRequest",
			"PlacerOrderNumberImagingServiceRequestRetiredRET",
			"FillerOrderNumberImagingServiceRequestRetiredRET",
			"OrderEnteredBy", "OrderEntererLocation",
			"OrderCallbackPhoneNumber",
			"PlacerOrderNumberImagingServiceRequest",
			"FillerOrderNumberImagingServiceRequest",
			"ImagingServiceRequestComments",
			"ConfidentialityConstraintOnPatientDataDescription",
			"GeneralPurposeScheduledProcedureStepStatus",
			"GeneralPurposePerformedProcedureStepStatus",
			"GeneralPurposeScheduledProcedureStepPriority",
			"ScheduledProcessingApplicationsCodeSequence",
			"ScheduledProcedureStepStartDateAndTime", "MultipleCopiesFlag",
			"PerformedProcessingApplicationsCodeSequence",
			"HumanPerformerCodeSequence",
			"ScheduledProcedureStepModificationDateAndTime",
			"ExpectedCompletionDateAndTime",
			"ResultingGeneralPurposePerformedProcedureStepsSequence",
			"ReferencedGeneralPurposeScheduledProcedureStepSequence",
			"ScheduledWorkitemCodeSequence", "PerformedWorkitemCodeSequence",
			"InputAvailabilityFlag", "InputInformationSequence",
			"RelevantInformationSequence",
			"ReferencedGeneralPurposeScheduledProcedureStepTransactionUID",
			"ScheduledStationNameCodeSequence",
			"ScheduledStationClassCodeSequence",
			"ScheduledStationGeographicLocationCodeSequence",
			"PerformedStationNameCodeSequence",
			"PerformedStationClassCodeSequence",
			"PerformedStationGeographicLocationCodeSequence",
			"RequestedSubsequentWorkitemCodeSequence",
			"NonDICOMOutputCodeSequence", "OutputInformationSequence",
			"ScheduledHumanPerformersSequence",
			"ActualHumanPerformersSequence", "HumanPerformerOrganization",
			"HumanPerformerName", "EntranceDoseInMGy",
			"ReferencedImageRealWorldValueMappingSequence",
			"RealWorldValueMappingSequence", "PixelValueMappingCodeSequence",
			"LUTLabel", "RealWorldValueLastValueMapped",
			"RealWorldValueLUTData", "RealWorldValueFirstValueMapped",
			"RealWorldValueIntercept", "RealWorldValueSlope",
			"RelationshipType", "VerifyingOrganization",
			"VerificationDateTime", "ObservationDateTime", "ValueType",
			"ConceptNameCodeSequence", "ContinuityOfContent",
			"VerifyingObserverSequence", "VerifyingObserverName",
			"AuthorObserverSequence", "ParticipantSequence",
			"CustodialOrganizationSequence", "ParticipationType",
			"ParticipationDateTime", "ObserverType",
			"VerifyingObserverIdentificationCodeSequence",
			"EquivalentCDADocumentSequenceRET", "ReferencedWaveformChannels",
			"DateTime", "Date", "Time", "PersonName", "UID",
			"TemporalRangeType", "ReferencedSamplePositions",
			"ReferencedFrameNumbers", "ReferencedTimeOffsets",
			"ReferencedDateTime", "TextValue", "ConceptCodeSequence",
			"PurposeOfReferenceCodeSequence", "AnnotationGroupNumber",
			"ModifierCodeSequence", "MeasuredValueSequence",
			"NumericValueQualifierCodeSequence", "NumericValue",
			"AddressTrialRET", "TelephoneNumberTrialRET",
			"PredecessorDocumentsSequence", "ReferencedRequestSequence",
			"PerformedProcedureCodeSequence",
			"CurrentRequestedProcedureEvidenceSequence",
			"PertinentOtherEvidenceSequence",
			"HL7StructuredDocumentReferenceSequence", "CompletionFlag",
			"CompletionFlagDescription", "VerificationFlag",
			"ArchiveRequested", "ContentTemplateSequence",
			"IdenticalDocumentsSequence", "ContentSequence",
			"AnnotationSequence", "TemplateIdentifier", "TemplateVersionRET",
			"TemplateLocalVersionRET", "TemplateExtensionFlagRET",
			"TemplateExtensionOrganizationUIDRET",
			"TemplateExtensionCreatorUIDRET",
			"ReferencedContentItemIdentifier", "HL7InstanceIdentifier",
			"HL7DocumentEffectiveTime", "HL7DocumentTypeCodeSequence",
			"RetrieveURI", "DocumentTitle", "EncapsulatedDocument",
			"MIMETypeOfEncapsulatedDocument", "SourceInstanceSequence",
			"ListOfMIMETypes", "ProductPackageIdentifier",
			"SubstanceAdministrationApproval",
			"ApprovalStatusFurtherDescription", "ApprovalStatusDateTime",
			"ProductTypeCodeSequence", "ProductName", "ProductDescription",
			"ProductLotIdentifier", "ProductExpirationDateTime",
			"SubstanceAdministrationDateTime", "SubstanceAdministrationNotes",
			"SubstanceAdministrationDeviceID", "ProductParameterSequence",
			"SubstanceAdministrationParameterSequence", "LensDescription",
			"RightLensSequence", "LeftLensSequence",
			"UnspecifiedLateralityLensSequence", "CylinderSequence",
			"PrismSequence", "HorizontalPrismPower", "HorizontalPrismBase",
			"VerticalPrismPower", "VerticalPrismBase", "LensSegmentType",
			"OpticalTransmittance", "ChannelWidth", "PupilSize", "CornealSize",
			"AutorefractionRightEyeSequence", "AutorefractionLeftEyeSequence",
			"DistancePupillaryDistance", "NearPupillaryDistance",
			"IntermediatePupillaryDistance", "OtherPupillaryDistance",
			"KeratometryRightEyeSequence", "KeratometryLeftEyeSequence",
			"SteepKeratometricAxisSequence", "RadiusOfCurvature",
			"KeratometricPower", "KeratometricAxis",
			"FlatKeratometricAxisSequence", "BackgroundColor", "Optotype",
			"OptotypePresentation", "SubjectiveRefractionRightEyeSequence",
			"SubjectiveRefractionLeftEyeSequence", "AddNearSequence",
			"AddIntermediateSequence", "AddOtherSequence", "AddPower",
			"ViewingDistance", "VisualAcuityTypeCodeSequence",
			"VisualAcuityRightEyeSequence", "VisualAcuityLeftEyeSequence",
			"VisualAcuityBothEyesOpenSequence", "ViewingDistanceType",
			"VisualAcuityModifiers", "DecimalVisualAcuity",
			"OptotypeDetailedDefinition",
			"ReferencedRefractiveMeasurementsSequence", "SpherePower",
			"CylinderPower", "CalibrationImage", "DeviceSequence",
			"DeviceLength", "DeviceDiameter", "DeviceDiameterUnits",
			"DeviceVolume", "IntermarkerDistance", "DeviceDescription",
			"EnergyWindowVector", "NumberOfEnergyWindows",
			"EnergyWindowInformationSequence", "EnergyWindowRangeSequence",
			"EnergyWindowLowerLimit", "EnergyWindowUpperLimit",
			"RadiopharmaceuticalInformationSequence", "ResidualSyringeCounts",
			"EnergyWindowName", "DetectorVector", "NumberOfDetectors",
			"DetectorInformationSequence", "PhaseVector", "NumberOfPhases",
			"PhaseInformationSequence", "NumberOfFramesInPhase", "PhaseDelay",
			"PauseBetweenFrames", "PhaseDescription", "RotationVector",
			"NumberOfRotations", "RotationInformationSequence",
			"NumberOfFramesInRotation", "RRIntervalVector",
			"NumberOfRRIntervals", "GatedInformationSequence",
			"DataInformationSequence", "TimeSlotVector", "NumberOfTimeSlots",
			"TimeSlotInformationSequence", "TimeSlotTime", "SliceVector",
			"NumberOfSlices", "AngularViewVector", "TimeSliceVector",
			"NumberOfTimeSlices", "StartAngle", "TypeOfDetectorMotion",
			"TriggerVector", "NumberOfTriggersInPhase", "ViewCodeSequence",
			"ViewModifierCodeSequence", "RadionuclideCodeSequence",
			"AdministrationRouteCodeSequence",
			"RadiopharmaceuticalCodeSequence", "CalibrationDataSequence",
			"EnergyWindowNumber", "ImageID", "PatientOrientationCodeSequence",
			"PatientOrientationModifierCodeSequence",
			"PatientGantryRelationshipCodeSequence",
			"SliceProgressionDirection", "SeriesType", "Units", "CountsSource",
			"ReprojectionMethod", "RandomsCorrectionMethod",
			"AttenuationCorrectionMethod", "DecayCorrection",
			"ReconstructionMethod", "DetectorLinesOfResponseUsed",
			"ScatterCorrectionMethod", "AxialAcceptance", "AxialMash",
			"TransverseMash", "DetectorElementSize", "CoincidenceWindowWidth",
			"SecondaryCountsType", "FrameReferenceTime",
			"PrimaryPromptsCountsAccumulated", "SecondaryCountsAccumulated",
			"SliceSensitivityFactor", "DecayFactor", "DoseCalibrationFactor",
			"ScatterFractionFactor", "DeadTimeFactor", "ImageIndex",
			"CountsIncludedRET", "DeadTimeCorrectionFlagRET",
			"HistogramSequence", "HistogramNumberOfBins",
			"HistogramFirstBinValue", "HistogramLastBinValue",
			"HistogramBinWidth", "HistogramExplanation", "HistogramData",
			"SegmentationType", "SegmentSequence",
			"SegmentedPropertyCategoryCodeSequence", "SegmentNumber",
			"SegmentLabel", "SegmentDescription", "SegmentAlgorithmType",
			"SegmentAlgorithmName", "SegmentIdentificationSequence",
			"ReferencedSegmentNumber", "RecommendedDisplayGrayscaleValue",
			"RecommendedDisplayCIELabValue", "MaximumFractionalValue",
			"SegmentedPropertyTypeCodeSequence", "SegmentationFractionalType",
			"DeformableRegistrationSequence", "SourceFrameOfReferenceUID",
			"DeformableRegistrationGridSequence", "GridDimensions",
			"GridResolution", "VectorGridData",
			"PreDeformationMatrixRegistrationSequence",
			"PostDeformationMatrixRegistrationSequence",
			"GraphicAnnotationSequence", "GraphicLayer",
			"BoundingBoxAnnotationUnits", "AnchorPointAnnotationUnits",
			"GraphicAnnotationUnits", "UnformattedTextValue",
			"TextObjectSequence", "GraphicObjectSequence",
			"BoundingBoxTopLeftHandCorner", "BoundingBoxBottomRightHandCorner",
			"BoundingBoxTextHorizontalJustification", "AnchorPoint",
			"AnchorPointVisibility", "GraphicDimensions",
			"NumberOfGraphicPoints", "GraphicData", "GraphicType",
			"GraphicFilled", "ImageRotationRetiredRET", "ImageHorizontalFlip",
			"ImageRotation", "DisplayedAreaTopLeftHandCornerTrialRET",
			"DisplayedAreaBottomRightHandCornerTrialRET",
			"DisplayedAreaTopLeftHandCorner",
			"DisplayedAreaBottomRightHandCorner",
			"DisplayedAreaSelectionSequence", "GraphicLayerSequence",
			"GraphicLayerOrder",
			"GraphicLayerRecommendedDisplayGrayscaleValue",
			"GraphicLayerRecommendedDisplayRGBValueRET",
			"GraphicLayerDescription", "ContentLabel", "ContentDescription",
			"PresentationCreationDate", "PresentationCreationTime",
			"ContentCreatorName", "ContentCreatorIdentificationCodeSequence",
			"PresentationSizeMode", "PresentationPixelSpacing",
			"PresentationPixelAspectRatio",
			"PresentationPixelMagnificationRatio", "ShapeType",
			"RegistrationSequence", "MatrixRegistrationSequence",
			"MatrixSequence", "FrameOfReferenceTransformationMatrixType",
			"RegistrationTypeCodeSequence", "FiducialDescription",
			"FiducialIdentifier", "FiducialIdentifierCodeSequence",
			"ContourUncertaintyRadius", "UsedFiducialsSequence",
			"GraphicCoordinatesDataSequence", "FiducialUID",
			"FiducialSetSequence", "FiducialSequence",
			"GraphicLayerRecommendedDisplayCIELabValue", "BlendingSequence",
			"RelativeOpacity", "ReferencedSpatialRegistrationSequence",
			"BlendingPosition", "HangingProtocolName",
			"HangingProtocolDescription", "HangingProtocolLevel",
			"HangingProtocolCreator", "HangingProtocolCreationDateTime",
			"HangingProtocolDefinitionSequence",
			"HangingProtocolUserIdentificationCodeSequence",
			"HangingProtocolUserGroupName", "SourceHangingProtocolSequence",
			"NumberOfPriorsReferenced", "ImageSetsSequence",
			"ImageSetSelectorSequence", "ImageSetSelectorUsageFlag",
			"SelectorAttribute", "SelectorValueNumber",
			"TimeBasedImageSetsSequence", "ImageSetNumber",
			"ImageSetSelectorCategory", "RelativeTime", "RelativeTimeUnits",
			"AbstractPriorValue", "AbstractPriorCodeSequence", "ImageSetLabel",
			"SelectorAttributeVR", "SelectorSequencePointer",
			"SelectorSequencePointerPrivateCreator",
			"SelectorAttributePrivateCreator", "SelectorATValue",
			"SelectorCSValue", "SelectorISValue", "SelectorLOValue",
			"SelectorLTValue", "SelectorPNValue", "SelectorSHValue",
			"SelectorSTValue", "SelectorUTValue", "SelectorDSValue",
			"SelectorFDValue", "SelectorFLValue", "SelectorULValue",
			"SelectorUSValue", "SelectorSLValue", "SelectorSSValue",
			"SelectorCodeSequenceValue", "NumberOfScreens",
			"NominalScreenDefinitionSequence", "NumberOfVerticalPixels",
			"NumberOfHorizontalPixels", "DisplayEnvironmentSpatialPosition",
			"ScreenMinimumGrayscaleBitDepth", "ScreenMinimumColorBitDepth",
			"ApplicationMaximumRepaintTime", "DisplaySetsSequence",
			"DisplaySetNumber", "DisplaySetLabel",
			"DisplaySetPresentationGroup",
			"DisplaySetPresentationGroupDescription",
			"PartialDataDisplayHandling", "SynchronizedScrollingSequence",
			"DisplaySetScrollingGroup", "NavigationIndicatorSequence",
			"NavigationDisplaySet", "ReferenceDisplaySets",
			"ImageBoxesSequence", "ImageBoxNumber", "ImageBoxLayoutType",
			"ImageBoxTileHorizontalDimension", "ImageBoxTileVerticalDimension",
			"ImageBoxScrollDirection", "ImageBoxSmallScrollType",
			"ImageBoxSmallScrollAmount", "ImageBoxLargeScrollType",
			"ImageBoxLargeScrollAmount", "ImageBoxOverlapPriority",
			"CineRelativeToRealTime", "FilterOperationsSequence",
			"FilterbyCategory", "FilterbyAttributePresence",
			"FilterbyOperator", "BlendingOperationType",
			"ReformattingOperationType", "ReformattingThickness",
			"ReformattingInterval",
			"ReformattingOperationInitialViewDirection", "_3DRenderingType",
			"SortingOperationsSequence", "SortbyCategory", "SortingDirection",
			"DisplaySetPatientOrientation", "VOIType", "PseudocolorType",
			"ShowGrayscaleInverted", "ShowImageTrueSizeFlag",
			"ShowGraphicAnnotationFlag", "ShowPatientDemographicsFlag",
			"ShowAcquisitionTechniquesFlag",
			"DisplaySetHorizontalJustification",
			"DisplaySetVerticalJustification", "UnifiedProcedureStepState",
			"UPSProgressInformationSequence", "UnifiedProcedureStepProgress",
			"UnifiedProcedureStepProgressDescription",
			"UnifiedProcedureStepCommunicationsURISequence", "ContactURI",
			"ContactDisplayName",
			"UnifiedProcedureStepDiscontinuationReasonCodeSequence",
			"BeamTaskSequence", "BeamTaskType", "BeamOrderIndex",
			"DeliveryVerificationImageSequence", "VerificationImageTiming",
			"DoubleExposureFlag", "DoubleExposureOrdering",
			"DoubleExposureMeterset", "DoubleExposureFieldDelta",
			"RelatedReferenceRTImageSequence",
			"GeneralMachineVerificationSequence",
			"ConventionalMachineVerificationSequence",
			"IonMachineVerificationSequence", "FailedAttributesSequence",
			"OverriddenAttributesSequence",
			"ConventionalControlPointVerificationSequence",
			"IonControlPointVerificationSequence",
			"AttributeOccurrenceSequence", "AttributeOccurrencePointer",
			"AttributeItemSelector", "AttributeOccurrencePrivateCreator",
			"ScheduledProcedureStepPriority", "WorklistLabel",
			"ProcedureStepLabel", "ScheduledProcessingParametersSequence",
			"PerformedProcessingParametersSequence",
			"UPSPerformedProcedureSequence", "RelatedProcedureStepSequence",
			"ProcedureStepRelationshipType", "DeletionLock", "ReceivingAE",
			"RequestingAE", "ReasonForCancellation", "SCPStatus",
			"SubscriptionListStatus", "UPSListStatus", "StorageMediaFilesetID",
			"StorageMediaFilesetUID", "IconImageSequence", "TopicTitleRET",
			"TopicSubjectRET", "TopicAuthorRET", "TopicKeywordsRET",
			"SOPInstanceStatus", "SOPAuthorizationDateAndTime",
			"SOPAuthorizationComment",
			"AuthorizationEquipmentCertificationNumber", "MACIDNumber",
			"MACCalculationTransferSyntaxUID", "MACAlgorithm",
			"DataElementsSigned", "DigitalSignatureUID",
			"DigitalSignatureDateTime", "CertificateType",
			"CertificateOfSigner", "Signature", "CertifiedTimestampType",
			"CertifiedTimestamp", "DigitalSignaturePurposeCodeSequence",
			"ReferencedDigitalSignatureSequence",
			"ReferencedSOPInstanceMACSequence", "MAC",
			"EncryptedAttributesSequence", "EncryptedContentTransferSyntaxUID",
			"EncryptedContent", "ModifiedAttributesSequence",
			"OriginalAttributesSequence", "AttributeModificationDateTime",
			"ModifyingSystem", "SourceOfPreviousValues",
			"ReasonForTheAttributeModification", "EscapeTripletRET",
			"RunLengthTripletRET", "HuffmanTableSizeRET",
			"HuffmanTableTripletRET", "ShiftTableSizeRET",
			"ShiftTableTripletRET", "ZonalMapRET", "NumberOfCopies",
			"PrinterConfigurationSequence", "PrintPriority", "MediumType",
			"FilmDestination", "FilmSessionLabel", "MemoryAllocation",
			"MaximumMemoryAllocation", "ColorImagePrintingFlagRET",
			"CollationFlagRET", "AnnotationFlagRET", "ImageOverlayFlagRET",
			"PresentationLUTFlagRET", "ImageBoxPresentationLUTFlagRET",
			"MemoryBitDepth", "PrintingBitDepth", "MediaInstalledSequence",
			"OtherMediaAvailableSequence",
			"SupportedImageDisplayFormatsSequence",
			"ReferencedFilmBoxSequence", "ReferencedStoredPrintSequenceRET",
			"ImageDisplayFormat", "AnnotationDisplayFormatID",
			"FilmOrientation", "FilmSizeID", "PrinterResolutionID",
			"DefaultPrinterResolutionID", "MagnificationType", "SmoothingType",
			"DefaultMagnificationType", "OtherMagnificationTypesAvailable",
			"DefaultSmoothingType", "OtherSmoothingTypesAvailable",
			"BorderDensity", "EmptyImageDensity", "MinDensity", "MaxDensity",
			"Trim", "ConfigurationInformation",
			"ConfigurationInformationDescription", "MaximumCollatedFilms",
			"Illumination", "ReflectedAmbientLight", "PrinterPixelSpacing",
			"ReferencedFilmSessionSequence", "ReferencedImageBoxSequence",
			"ReferencedBasicAnnotationBoxSequence", "ImageBoxPosition",
			"Polarity", "RequestedImageSize", "RequestedDecimateCropBehavior",
			"RequestedResolutionID", "RequestedImageSizeFlag",
			"DecimateCropResult", "BasicGrayscaleImageSequence",
			"BasicColorImageSequence", "ReferencedImageOverlayBoxSequenceRET",
			"ReferencedVOILUTBoxSequenceRET", "AnnotationPosition",
			"TextString", "ReferencedOverlayPlaneSequenceRET",
			"ReferencedOverlayPlaneGroupsRET", "OverlayPixelDataSequenceRET",
			"OverlayMagnificationTypeRET", "OverlaySmoothingTypeRET",
			"OverlayOrImageMagnificationRET", "MagnifyToNumberOfColumnsRET",
			"OverlayForegroundDensityRET", "OverlayBackgroundDensityRET",
			"OverlayModeRET", "ThresholdDensityRET",
			"ReferencedImageBoxSequenceRetiredRET", "PresentationLUTSequence",
			"PresentationLUTShape", "ReferencedPresentationLUTSequence",
			"PrintJobIDRET", "ExecutionStatus", "ExecutionStatusInfo",
			"CreationDate", "CreationTime", "Originator", "DestinationAERET",
			"OwnerID", "NumberOfFilms",
			"ReferencedPrintJobSequencePullStoredPrintRET", "PrinterStatus",
			"PrinterStatusInfo", "PrinterName", "PrintQueueIDRET",
			"QueueStatusRET", "PrintJobDescriptionSequenceRET",
			"ReferencedPrintJobSequenceRET",
			"PrintManagementCapabilitiesSequenceRET",
			"PrinterCharacteristicsSequenceRET", "FilmBoxContentSequenceRET",
			"ImageBoxContentSequenceRET", "AnnotationContentSequenceRET",
			"ImageOverlayBoxContentSequenceRET",
			"PresentationLUTContentSequenceRET", "ProposedStudySequenceRET",
			"OriginalImageSequenceRET",
			"LabelUsingInformationExtractedFromInstances", "LabelText",
			"LabelStyleSelection", "MediaDisposition", "BarcodeValue",
			"BarcodeSymbology", "AllowMediaSplitting",
			"IncludeNonDICOMObjects", "IncludeDisplayApplication",
			"PreserveCompositeInstancesAfterMediaCreation",
			"TotalNumberOfPiecesOfMediaCreated",
			"RequestedMediaApplicationProfile",
			"ReferencedStorageMediaSequence", "FailureAttributes",
			"AllowLossyCompression", "RequestPriority", "RTImageLabel",
			"RTImageName", "RTImageDescription", "ReportedValuesOrigin",
			"RTImagePlane", "XRayImageReceptorTranslation",
			"XRayImageReceptorAngle", "RTImageOrientation",
			"ImagePlanePixelSpacing", "RTImagePosition",
			"RadiationMachineName", "RadiationMachineSAD",
			"RadiationMachineSSD", "RTImageSID",
			"SourceToReferenceObjectDistance", "FractionNumber",
			"ExposureSequence", "MetersetExposure", "DiaphragmPosition",
			"FluenceMapSequence", "FluenceDataSource", "FluenceDataScale",
			"DVHType", "DoseUnits", "DoseType", "DoseComment",
			"NormalizationPoint", "DoseSummationType", "GridFrameOffsetVector",
			"DoseGridScaling", "RTDoseROISequence", "DoseValue",
			"TissueHeterogeneityCorrection", "DVHNormalizationPoint",
			"DVHNormalizationDoseValue", "DVHSequence", "DVHDoseScaling",
			"DVHVolumeUnits", "DVHNumberOfBins", "DVHData",
			"DVHReferencedROISequence", "DVHROIContributionType",
			"DVHMinimumDose", "DVHMaximumDose", "DVHMeanDose",
			"StructureSetLabel", "StructureSetName", "StructureSetDescription",
			"StructureSetDate", "StructureSetTime",
			"ReferencedFrameOfReferenceSequence", "RTReferencedStudySequence",
			"RTReferencedSeriesSequence", "ContourImageSequence",
			"StructureSetROISequence", "ROINumber",
			"ReferencedFrameOfReferenceUID", "ROIName", "ROIDescription",
			"ROIDisplayColor", "ROIVolume", "RTRelatedROISequence",
			"RTROIRelationship", "ROIGenerationAlgorithm",
			"ROIGenerationDescription", "ROIContourSequence",
			"ContourSequence", "ContourGeometricType", "ContourSlabThickness",
			"ContourOffsetVector", "NumberOfContourPoints", "ContourNumber",
			"AttachedContours", "ContourData", "RTROIObservationsSequence",
			"ObservationNumber", "ReferencedROINumber", "ROIObservationLabel",
			"RTROIIdentificationCodeSequence", "ROIObservationDescription",
			"RelatedRTROIObservationsSequence", "RTROIInterpretedType",
			"ROIInterpreter", "ROIPhysicalPropertiesSequence",
			"ROIPhysicalProperty", "ROIPhysicalPropertyValue",
			"ROIElementalCompositionSequence",
			"ROIElementalCompositionAtomicNumber",
			"ROIElementalCompositionAtomicMassFraction",
			"FrameOfReferenceRelationshipSequence",
			"RelatedFrameOfReferenceUID", "FrameOfReferenceTransformationType",
			"FrameOfReferenceTransformationMatrix",
			"FrameOfReferenceTransformationComment",
			"MeasuredDoseReferenceSequence", "MeasuredDoseDescription",
			"MeasuredDoseType", "MeasuredDoseValue",
			"TreatmentSessionBeamSequence", "TreatmentSessionIonBeamSequence",
			"CurrentFractionNumber", "TreatmentControlPointDate",
			"TreatmentControlPointTime", "TreatmentTerminationStatus",
			"TreatmentTerminationCode", "TreatmentVerificationStatus",
			"ReferencedTreatmentRecordSequence", "SpecifiedPrimaryMeterset",
			"SpecifiedSecondaryMeterset", "DeliveredPrimaryMeterset",
			"DeliveredSecondaryMeterset", "SpecifiedTreatmentTime",
			"DeliveredTreatmentTime", "ControlPointDeliverySequence",
			"IonControlPointDeliverySequence", "SpecifiedMeterset",
			"DeliveredMeterset", "MetersetRateSet", "MetersetRateDelivered",
			"ScanSpotMetersetsDelivered", "DoseRateDelivered",
			"TreatmentSummaryCalculatedDoseReferenceSequence",
			"CumulativeDoseToDoseReference", "FirstTreatmentDate",
			"MostRecentTreatmentDate", "NumberOfFractionsDelivered",
			"OverrideSequence", "ParameterSequencePointer",
			"OverrideParameterPointer", "ParameterItemIndex",
			"MeasuredDoseReferenceNumber", "ParameterPointer",
			"OverrideReason", "CorrectedParameterSequence", "CorrectionValue",
			"CalculatedDoseReferenceSequence", "CalculatedDoseReferenceNumber",
			"CalculatedDoseReferenceDescription",
			"CalculatedDoseReferenceDoseValue", "StartMeterset", "EndMeterset",
			"ReferencedMeasuredDoseReferenceSequence",
			"ReferencedMeasuredDoseReferenceNumber",
			"ReferencedCalculatedDoseReferenceSequence",
			"ReferencedCalculatedDoseReferenceNumber",
			"BeamLimitingDeviceLeafPairsSequence", "RecordedWedgeSequence",
			"RecordedCompensatorSequence", "RecordedBlockSequence",
			"TreatmentSummaryMeasuredDoseReferenceSequence",
			"RecordedSnoutSequence", "RecordedRangeShifterSequence",
			"RecordedLateralSpreadingDeviceSequence",
			"RecordedRangeModulatorSequence", "RecordedSourceSequence",
			"SourceSerialNumber", "TreatmentSessionApplicationSetupSequence",
			"ApplicationSetupCheck", "RecordedBrachyAccessoryDeviceSequence",
			"ReferencedBrachyAccessoryDeviceNumber", "RecordedChannelSequence",
			"SpecifiedChannelTotalTime", "DeliveredChannelTotalTime",
			"SpecifiedNumberOfPulses", "DeliveredNumberOfPulses",
			"SpecifiedPulseRepetitionInterval",
			"DeliveredPulseRepetitionInterval",
			"RecordedSourceApplicatorSequence",
			"ReferencedSourceApplicatorNumber",
			"RecordedChannelShieldSequence", "ReferencedChannelShieldNumber",
			"BrachyControlPointDeliveredSequence", "SafePositionExitDate",
			"SafePositionExitTime", "SafePositionReturnDate",
			"SafePositionReturnTime", "CurrentTreatmentStatus",
			"TreatmentStatusComment", "FractionGroupSummarySequence",
			"ReferencedFractionNumber", "FractionGroupType",
			"BeamStopperPosition", "FractionStatusSummarySequence",
			"TreatmentDate", "TreatmentTime", "RTPlanLabel", "RTPlanName",
			"RTPlanDescription", "RTPlanDate", "RTPlanTime",
			"TreatmentProtocols", "PlanIntent", "TreatmentSites",
			"RTPlanGeometry", "PrescriptionDescription",
			"DoseReferenceSequence", "DoseReferenceNumber", "DoseReferenceUID",
			"DoseReferenceStructureType", "NominalBeamEnergyUnit",
			"DoseReferenceDescription", "DoseReferencePointCoordinates",
			"NominalPriorDose", "DoseReferenceType", "ConstraintWeight",
			"DeliveryWarningDose", "DeliveryMaximumDose", "TargetMinimumDose",
			"TargetPrescriptionDose", "TargetMaximumDose",
			"TargetUnderdoseVolumeFraction", "OrganAtRiskFullvolumeDose",
			"OrganAtRiskLimitDose", "OrganAtRiskMaximumDose",
			"OrganAtRiskOverdoseVolumeFraction", "ToleranceTableSequence",
			"ToleranceTableNumber", "ToleranceTableLabel",
			"GantryAngleTolerance", "BeamLimitingDeviceAngleTolerance",
			"BeamLimitingDeviceToleranceSequence",
			"BeamLimitingDevicePositionTolerance", "SnoutPositionTolerance",
			"PatientSupportAngleTolerance", "TableTopEccentricAngleTolerance",
			"TableTopPitchAngleTolerance", "TableTopRollAngleTolerance",
			"TableTopVerticalPositionTolerance",
			"TableTopLongitudinalPositionTolerance",
			"TableTopLateralPositionTolerance", "RTPlanRelationship",
			"FractionGroupSequence", "FractionGroupNumber",
			"FractionGroupDescription", "NumberOfFractionsPlanned",
			"NumberOfFractionPatternDigitsPerDay", "RepeatFractionCycleLength",
			"FractionPattern", "NumberOfBeams", "BeamDoseSpecificationPoint",
			"BeamDose", "BeamMeterset", "BeamDosePointDepth",
			"BeamDosePointEquivalentDepth", "BeamDosePointSSD",
			"NumberOfBrachyApplicationSetups",
			"BrachyApplicationSetupDoseSpecificationPoint",
			"BrachyApplicationSetupDose", "BeamSequence",
			"TreatmentMachineName", "PrimaryDosimeterUnit",
			"SourceAxisDistance", "BeamLimitingDeviceSequence",
			"RTBeamLimitingDeviceType", "SourceToBeamLimitingDeviceDistance",
			"IsocenterToBeamLimitingDeviceDistance", "NumberOfLeafJawPairs",
			"LeafPositionBoundaries", "BeamNumber", "BeamName",
			"BeamDescription", "BeamType", "RadiationType",
			"HighDoseTechniqueType", "ReferenceImageNumber",
			"PlannedVerificationImageSequence",
			"ImagingDeviceSpecificAcquisitionParameters",
			"TreatmentDeliveryType", "NumberOfWedges", "WedgeSequence",
			"WedgeNumber", "WedgeType", "WedgeID", "WedgeAngle", "WedgeFactor",
			"TotalWedgeTrayWaterEquivalentThickness", "WedgeOrientation",
			"IsocenterToWedgeTrayDistance", "SourceToWedgeTrayDistance",
			"WedgeThinEdgePosition", "BolusID", "BolusDescription",
			"NumberOfCompensators", "MaterialID", "TotalCompensatorTrayFactor",
			"CompensatorSequence", "CompensatorNumber", "CompensatorID",
			"SourceToCompensatorTrayDistance", "CompensatorRows",
			"CompensatorColumns", "CompensatorPixelSpacing",
			"CompensatorPosition", "CompensatorTransmissionData",
			"CompensatorThicknessData", "NumberOfBoli", "CompensatorType",
			"NumberOfBlocks", "TotalBlockTrayFactor",
			"TotalBlockTrayWaterEquivalentThickness", "BlockSequence",
			"BlockTrayID", "SourceToBlockTrayDistance",
			"IsocenterToBlockTrayDistance", "BlockType", "AccessoryCode",
			"BlockDivergence", "BlockMountingPosition", "BlockNumber",
			"BlockName", "BlockThickness", "BlockTransmission",
			"BlockNumberOfPoints", "BlockData", "ApplicatorSequence",
			"ApplicatorID", "ApplicatorType", "ApplicatorDescription",
			"CumulativeDoseReferenceCoefficient",
			"FinalCumulativeMetersetWeight", "NumberOfControlPoints",
			"ControlPointSequence", "ControlPointIndex", "NominalBeamEnergy",
			"DoseRateSet", "WedgePositionSequence", "WedgePosition",
			"BeamLimitingDevicePositionSequence", "LeafJawPositions",
			"GantryAngle", "GantryRotationDirection",
			"BeamLimitingDeviceAngle", "BeamLimitingDeviceRotationDirection",
			"PatientSupportAngle", "PatientSupportRotationDirection",
			"TableTopEccentricAxisDistance", "TableTopEccentricAngle",
			"TableTopEccentricRotationDirection", "TableTopVerticalPosition",
			"TableTopLongitudinalPosition", "TableTopLateralPosition",
			"IsocenterPosition", "SurfaceEntryPoint",
			"SourceToSurfaceDistance", "CumulativeMetersetWeight",
			"TableTopPitchAngle", "TableTopPitchRotationDirection",
			"TableTopRollAngle", "TableTopRollRotationDirection",
			"HeadFixationAngle", "GantryPitchAngle",
			"GantryPitchRotationDirection", "GantryPitchAngleTolerance",
			"PatientSetupSequence", "PatientSetupNumber", "PatientSetupLabel",
			"PatientAdditionalPosition", "FixationDeviceSequence",
			"FixationDeviceType", "FixationDeviceLabel",
			"FixationDeviceDescription", "FixationDevicePosition",
			"FixationDevicePitchAngle", "FixationDeviceRollAngle",
			"ShieldingDeviceSequence", "ShieldingDeviceType",
			"ShieldingDeviceLabel", "ShieldingDeviceDescription",
			"ShieldingDevicePosition", "SetupTechnique",
			"SetupTechniqueDescription", "SetupDeviceSequence",
			"SetupDeviceType", "SetupDeviceLabel", "SetupDeviceDescription",
			"SetupDeviceParameter", "SetupReferenceDescription",
			"TableTopVerticalSetupDisplacement",
			"TableTopLongitudinalSetupDisplacement",
			"TableTopLateralSetupDisplacement", "BrachyTreatmentTechnique",
			"BrachyTreatmentType", "TreatmentMachineSequence",
			"SourceSequence", "SourceNumber", "SourceType",
			"SourceManufacturer", "ActiveSourceDiameter", "ActiveSourceLength",
			"SourceEncapsulationNominalThickness",
			"SourceEncapsulationNominalTransmission", "SourceIsotopeName",
			"SourceIsotopeHalfLife", "SourceStrengthUnits",
			"ReferenceAirKermaRate", "SourceStrength",
			"SourceStrengthReferenceDate", "SourceStrengthReferenceTime",
			"ApplicationSetupSequence", "ApplicationSetupType",
			"ApplicationSetupNumber", "ApplicationSetupName",
			"ApplicationSetupManufacturer", "TemplateNumber", "TemplateType",
			"TemplateName", "TotalReferenceAirKerma",
			"BrachyAccessoryDeviceSequence", "BrachyAccessoryDeviceNumber",
			"BrachyAccessoryDeviceID", "BrachyAccessoryDeviceType",
			"BrachyAccessoryDeviceName",
			"BrachyAccessoryDeviceNominalThickness",
			"BrachyAccessoryDeviceNominalTransmission", "ChannelSequence",
			"ChannelNumber", "ChannelLength", "ChannelTotalTime",
			"SourceMovementType", "NumberOfPulses", "PulseRepetitionInterval",
			"SourceApplicatorNumber", "SourceApplicatorID",
			"SourceApplicatorType", "SourceApplicatorName",
			"SourceApplicatorLength", "SourceApplicatorManufacturer",
			"SourceApplicatorWallNominalThickness",
			"SourceApplicatorWallNominalTransmission",
			"SourceApplicatorStepSize", "TransferTubeNumber",
			"TransferTubeLength", "ChannelShieldSequence",
			"ChannelShieldNumber", "ChannelShieldID", "ChannelShieldName",
			"ChannelShieldNominalThickness",
			"ChannelShieldNominalTransmission", "FinalCumulativeTimeWeight",
			"BrachyControlPointSequence", "ControlPointRelativePosition",
			"ControlPoint3DPosition", "CumulativeTimeWeight",
			"CompensatorDivergence", "CompensatorMountingPosition",
			"SourceToCompensatorDistance",
			"TotalCompensatorTrayWaterEquivalentThickness",
			"IsocenterToCompensatorTrayDistance", "CompensatorColumnOffset",
			"IsocenterToCompensatorDistances",
			"CompensatorRelativeStoppingPowerRatio",
			"CompensatorMillingToolDiameter", "IonRangeCompensatorSequence",
			"CompensatorDescription", "RadiationMassNumber",
			"RadiationAtomicNumber", "RadiationChargeState", "ScanMode",
			"VirtualSourceAxisDistances", "SnoutSequence", "SnoutPosition",
			"SnoutID", "NumberOfRangeShifters", "RangeShifterSequence",
			"RangeShifterNumber", "RangeShifterID", "RangeShifterType",
			"RangeShifterDescription", "NumberOfLateralSpreadingDevices",
			"LateralSpreadingDeviceSequence", "LateralSpreadingDeviceNumber",
			"LateralSpreadingDeviceID", "LateralSpreadingDeviceType",
			"LateralSpreadingDeviceDescription",
			"LateralSpreadingDeviceWaterEquivalentThickness",
			"NumberOfRangeModulators", "RangeModulatorSequence",
			"RangeModulatorNumber", "RangeModulatorID", "RangeModulatorType",
			"RangeModulatorDescription", "BeamCurrentModulationID",
			"PatientSupportType", "PatientSupportID",
			"PatientSupportAccessoryCode", "FixationLightAzimuthalAngle",
			"FixationLightPolarAngle", "MetersetRate",
			"RangeShifterSettingsSequence", "RangeShifterSetting",
			"IsocenterToRangeShifterDistance",
			"RangeShifterWaterEquivalentThickness",
			"LateralSpreadingDeviceSettingsSequence",
			"LateralSpreadingDeviceSetting",
			"IsocenterToLateralSpreadingDeviceDistance",
			"RangeModulatorSettingsSequence", "RangeModulatorGatingStartValue",
			"RangeModulatorGatingStopValue",
			"RangeModulatorGatingStartWaterEquivalentThickness",
			"RangeModulatorGatingStopWaterEquivalentThickness",
			"IsocenterToRangeModulatorDistance", "ScanSpotTuneID",
			"NumberOfScanSpotPositions", "ScanSpotPositionMap",
			"ScanSpotMetersetWeights", "ScanningSpotSize", "NumberOfPaintings",
			"IonToleranceTableSequence", "IonBeamSequence",
			"IonBeamLimitingDeviceSequence", "IonBlockSequence",
			"IonControlPointSequence", "IonWedgeSequence",
			"IonWedgePositionSequence", "ReferencedSetupImageSequence",
			"SetupImageComment", "MotionSynchronizationSequence",
			"ControlPointOrientation", "GeneralAccessorySequence",
			"GeneralAccessoryID", "GeneralAccessoryDescription",
			"GeneralAccessoryType", "GeneralAccessoryNumber",
			"ReferencedRTPlanSequence", "ReferencedBeamSequence",
			"ReferencedBeamNumber", "ReferencedReferenceImageNumber",
			"StartCumulativeMetersetWeight", "EndCumulativeMetersetWeight",
			"ReferencedBrachyApplicationSetupSequence",
			"ReferencedBrachyApplicationSetupNumber", "ReferencedSourceNumber",
			"ReferencedFractionGroupSequence", "ReferencedFractionGroupNumber",
			"ReferencedVerificationImageSequence",
			"ReferencedReferenceImageSequence",
			"ReferencedDoseReferenceSequence", "ReferencedDoseReferenceNumber",
			"BrachyReferencedDoseReferenceSequence",
			"ReferencedStructureSetSequence", "ReferencedPatientSetupNumber",
			"ReferencedDoseSequence", "ReferencedToleranceTableNumber",
			"ReferencedBolusSequence", "ReferencedWedgeNumber",
			"ReferencedCompensatorNumber", "ReferencedBlockNumber",
			"ReferencedControlPointIndex", "ReferencedControlPointSequence",
			"ReferencedStartControlPointIndex",
			"ReferencedStopControlPointIndex", "ReferencedRangeShifterNumber",
			"ReferencedLateralSpreadingDeviceNumber",
			"ReferencedRangeModulatorNumber", "ApprovalStatus", "ReviewDate",
			"ReviewTime", "ReviewerName", "ArbitraryRET", "TextCommentsRET",
			"ResultsIDRET", "ResultsIDIssuerRET",
			"ReferencedInterpretationSequenceRET",
			"InterpretationRecordedDateRET", "InterpretationRecordedTimeRET",
			"InterpretationRecorderRET", "ReferenceToRecordedSoundRET",
			"InterpretationTranscriptionDateRET",
			"InterpretationTranscriptionTimeRET",
			"InterpretationTranscriberRET", "InterpretationTextRET",
			"InterpretationAuthorRET", "InterpretationApproverSequenceRET",
			"InterpretationApprovalDateRET", "InterpretationApprovalTimeRET",
			"PhysicianApprovingInterpretationRET",
			"InterpretationDiagnosisDescriptionRET",
			"InterpretationDiagnosisCodeSequenceRET",
			"ResultsDistributionListSequenceRET", "DistributionNameRET",
			"DistributionAddressRET", "InterpretationIDRET",
			"InterpretationIDIssuerRET", "InterpretationTypeIDRET",
			"InterpretationStatusIDRET", "ImpressionsRET",
			"ResultsCommentsRET", "MACParametersSequence",
			"CurveDimensionsRET", "NumberOfPointsRET", "TypeOfDataRET",
			"CurveDescriptionRET", "AxisUnitsRET", "AxisLabelsRET",
			"DataValueRepresentationRET", "MinimumCoordinateValueRET",
			"MaximumCoordinateValueRET", "CurveRangeRET",
			"CurveDataDescriptorRET", "CoordinateStartValueRET",
			"CoordinateStepValueRET", "CurveActivationLayerRET",
			"AudioTypeRET", "AudioSampleFormatRET", "NumberOfChannelsRET",
			"NumberOfSamplesRET", "SampleRateRET", "TotalTimeRET",
			"AudioSampleDataRET", "AudioCommentsRET", "CurveLabelRET",
			"CurveReferencedOverlaySequenceRET",
			"CurveReferencedOverlayGroupRET", "CurveDataRET",
			"SharedFunctionalGroupsSequence",
			"PerframeFunctionalGroupsSequence", "WaveformSequence",
			"ChannelMinimumValue", "ChannelMaximumValue",
			"WaveformBitsAllocated", "WaveformSampleInterpretation",
			"WaveformPaddingValue", "WaveformData",
			"FirstOrderPhaseCorrectionAngle", "SpectroscopyData",
			"OverlayRows", "OverlayColumns", "OverlayPlanesRET",
			"NumberOfFramesInOverlay", "OverlayDescription", "OverlayType",
			"OverlaySubtype", "OverlayOrigin", "ImageFrameOrigin",
			"OverlayPlaneOriginRET", "OverlayCompressionCodeRET",
			"OverlayCompressionOriginatorRET", "OverlayCompressionLabelRET",
			"OverlayCompressionDescriptionRET",
			"OverlayCompressionStepPointersRET", "OverlayRepeatIntervalRET",
			"OverlayBitsGroupedRET", "OverlayBitsAllocated",
			"OverlayBitPosition", "OverlayFormatRET", "OverlayLocationRET",
			"OverlayCodeLabelRET", "OverlayNumberOfTablesRET",
			"OverlayCodeTableLocationRET", "OverlayBitsForCodeWordRET",
			"OverlayActivationLayer", "OverlayDescriptorGrayRET",
			"OverlayDescriptorRedRET", "OverlayDescriptorGreenRET",
			"OverlayDescriptorBlueRET", "OverlaysGrayRET", "OverlaysRedRET",
			"OverlaysGreenRET", "OverlaysBlueRET", "ROIArea", "ROIMean",
			"ROIStandardDeviation", "OverlayLabel", "OverlayData",
			"OverlayCommentsRET", "PixelData", "CoefficientsSDVNRET",
			"CoefficientsSDHNRET", "CoefficientsSDDNRET",
			"VariablePixelDataRET", "VariableNextDataGroupRET",
			"VariableCoefficientsSDVNRET", "VariableCoefficientsSDHNRET",
			"VariableCoefficientsSDDNRET", "DigitalSignaturesSequence",
			"DataSetTrailingPadding", "Item", "ItemDelimitationItem",
			"SequenceDelimitationItem"};
	private String [] values;
	public boolean loadFileError = false;
	
	public int getTextsNo()
	{
		return tags.length;
	}

	public DicomHeader (File file) 
	{
			DicomFile dicomFile = new DicomFile (file);
			if (!dicomFile.loadFileError)
			{
				DicomObject dicomObject = dicomFile.getDicomObject();
				values = new String [tags.length];
				for (int i=0; i<values.length; i++)
				{
					try
					{
						values[i] = dicomObject.getString(Tag.forName(tags[i]));
					}
					catch (UnsupportedOperationException e) 
					{ 
						System.out.println ("Getting "+tags[i]+" value failed.");
					}
				}
				dicomFile = null;
				dicomObject = null;
			}
			else loadFileError = true;
	}
	
	public String [] getTags()
	{
		return tags;
	}
	
	public String [] getValues()
	{
		return values;
	}
}
