#ifndef __org_psystems_dicom_ooplugin_studymgr_webdicomplugin_idl__
#define __org_psystems_dicom_ooplugin_studymgr_webdicomplugin_idl__

#include <org/psystems/dicom/ooplugin/studymgr/XDicomplugin.idl>
module org { module psystems { module dicom { module ooplugin { module studymgr { 	

	service Webdicomplugin : org::psystems::dicom::ooplugin::studymgr::XDicomplugin {

	};

 }; }; }; }; };
#endif
