
package org.psystems.webdicom2.ws.client.stub;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Gate", targetNamespace = "http://ws.webdicom2.psystems.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Gate {


    /**
     * 
     * @param direction
     * @return
     *     returns org.psystems.webdicom2.ws.client.stub.Direction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendDirection", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.SendDirection")
    @ResponseWrapper(localName = "sendDirectionResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.SendDirectionResponse")
    public Direction sendDirection(
        @WebParam(name = "direction", targetNamespace = "")
        Direction direction);

    /**
     * 
     * @param misId
     * @return
     *     returns org.psystems.webdicom2.ws.client.stub.StudyResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompliteStudyResult", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetCompliteStudyResult")
    @ResponseWrapper(localName = "getCompliteStudyResultResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetCompliteStudyResultResponse")
    public StudyResult getCompliteStudyResult(
        @WebParam(name = "misId", targetNamespace = "")
        String misId);

    /**
     * 
     * @param content
     * @param misId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendPdf", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.SendPdf")
    @ResponseWrapper(localName = "sendPdfResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.SendPdfResponse")
    public String sendPdf(
        @WebParam(name = "misId", targetNamespace = "")
        String misId,
        @WebParam(name = "content", targetNamespace = "")
        byte[] content);

    /**
     * 
     * @param misId
     * @param resultStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendFinalResult", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.SendFinalResult")
    @ResponseWrapper(localName = "sendFinalResultResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.SendFinalResultResponse")
    public String sendFinalResult(
        @WebParam(name = "misId", targetNamespace = "")
        String misId,
        @WebParam(name = "resultStr", targetNamespace = "")
        String resultStr);

    /**
     * 
     * @param misId
     * @param fio
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendPhysician", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.SendPhysician")
    @ResponseWrapper(localName = "sendPhysicianResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.SendPhysicianResponse")
    public String sendPhysician(
        @WebParam(name = "misId", targetNamespace = "")
        String misId,
        @WebParam(name = "fio", targetNamespace = "")
        String fio);

    /**
     * 
     * @return
     *     returns java.util.List<org.psystems.webdicom2.ws.client.stub.RisCode>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRISCodes", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetRISCodes")
    @ResponseWrapper(localName = "getRISCodesResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetRISCodesResponse")
    public List<RisCode> getRISCodes();

    /**
     * 
     * @param misId
     * @return
     *     returns java.util.List<org.psystems.webdicom2.ws.client.stub.Dcm>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDCM", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetDCM")
    @ResponseWrapper(localName = "getDCMResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetDCMResponse")
    public List<Dcm> getDCM(
        @WebParam(name = "misId", targetNamespace = "")
        String misId);

    /**
     * 
     * @param misId
     * @param contentId
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDCMContent", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetDCMContent")
    @ResponseWrapper(localName = "getDCMContentResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetDCMContentResponse")
    public byte[] getDCMContent(
        @WebParam(name = "misId", targetNamespace = "")
        String misId,
        @WebParam(name = "contentId", targetNamespace = "")
        String contentId);

    /**
     * 
     * @param misId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeDirection", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.RemoveDirection")
    @ResponseWrapper(localName = "removeDirectionResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.RemoveDirectionResponse")
    public int removeDirection(
        @WebParam(name = "misId", targetNamespace = "")
        String misId);

    /**
     * 
     * @param content
     * @param misId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendImage", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.SendImage")
    @ResponseWrapper(localName = "sendImageResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.SendImageResponse")
    public String sendImage(
        @WebParam(name = "misId", targetNamespace = "")
        String misId,
        @WebParam(name = "content", targetNamespace = "")
        byte[] content);

    /**
     * 
     * @param dcmId
     * @return
     *     returns org.psystems.webdicom2.ws.client.stub.HashMap
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDCMTags", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetDCMTags")
    @ResponseWrapper(localName = "getDCMTagsResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetDCMTagsResponse")
    public HashMap getDCMTags(
        @WebParam(name = "dcmId", targetNamespace = "")
        String dcmId);

    /**
     * 
     * @param misId
     * @param date
     * @return
     *     returns java.util.List<org.psystems.webdicom2.ws.client.stub.Dcm>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDCMbyDate", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetDCMbyDate")
    @ResponseWrapper(localName = "getDCMbyDateResponse", targetNamespace = "http://ws.webdicom2.psystems.org/", className = "org.psystems.webdicom2.ws.client.stub.GetDCMbyDateResponse")
    public List<Dcm> getDCMbyDate(
        @WebParam(name = "misId", targetNamespace = "")
        String misId,
        @WebParam(name = "date", targetNamespace = "")
        String date);

}
