
package com.asutp.okocits3.ueh.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DataGateService", targetNamespace = "http://ws.ueh.okocits3.asutp.com/", wsdlLocation = "http://localhost:8080/okocits3-ueh-ws/DataGate?wsdl")
public class DataGateService
    extends Service
{

    private final static URL DATAGATESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.asutp.okocits3.ueh.ws.client.DataGateService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.asutp.okocits3.ueh.ws.client.DataGateService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/okocits3-ueh-ws/DataGate?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/okocits3-ueh-ws/DataGate?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATAGATESERVICE_WSDL_LOCATION = url;
    }

    public DataGateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataGateService() {
        super(DATAGATESERVICE_WSDL_LOCATION, new QName("http://ws.ueh.okocits3.asutp.com/", "DataGateService"));
    }

    /**
     * 
     * @return
     *     returns DataGate
     */
    @WebEndpoint(name = "DataGatePort")
    public DataGate getDataGatePort() {
        return super.getPort(new QName("http://ws.ueh.okocits3.asutp.com/", "DataGatePort"), DataGate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataGate
     */
    @WebEndpoint(name = "DataGatePort")
    public DataGate getDataGatePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.ueh.okocits3.asutp.com/", "DataGatePort"), DataGate.class, features);
    }

}
