
package sng.asuneft.atp.okocits3.ws.ueh.client.stub;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UEHGate", targetNamespace = "http://ueh.ws.okocits3.atp.asuneft.sng/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UEHGate {


    /**
     * 
     * @param calcgroup
     * @return
     *     returns sng.asuneft.atp.okocits3.ws.ueh.client.stub.CalcGroup
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newCalcGroup", targetNamespace = "http://ueh.ws.okocits3.atp.asuneft.sng/", className = "sng.asuneft.atp.okocits3.ws.ueh.client.stub.NewCalcGroup")
    @ResponseWrapper(localName = "newCalcGroupResponse", targetNamespace = "http://ueh.ws.okocits3.atp.asuneft.sng/", className = "sng.asuneft.atp.okocits3.ws.ueh.client.stub.NewCalcGroupResponse")
    public CalcGroup newCalcGroup(
        @WebParam(name = "calcgroup", targetNamespace = "")
        CalcGroupPI calcgroup);

    /**
     * 
     * @param idGroup
     * @return
     *     returns sng.asuneft.atp.okocits3.ws.ueh.client.stub.CalcGroup
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCalcGroup", targetNamespace = "http://ueh.ws.okocits3.atp.asuneft.sng/", className = "sng.asuneft.atp.okocits3.ws.ueh.client.stub.GetCalcGroup")
    @ResponseWrapper(localName = "getCalcGroupResponse", targetNamespace = "http://ueh.ws.okocits3.atp.asuneft.sng/", className = "sng.asuneft.atp.okocits3.ws.ueh.client.stub.GetCalcGroupResponse")
    public CalcGroup getCalcGroup(
        @WebParam(name = "idGroup", targetNamespace = "")
        int idGroup);

    /**
     * 
     * @param withlimit
     * @param filters
     * @return
     *     returns java.util.List<sng.asuneft.atp.okocits3.ws.ueh.client.stub.CalcGroup>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCalcGroups", targetNamespace = "http://ueh.ws.okocits3.atp.asuneft.sng/", className = "sng.asuneft.atp.okocits3.ws.ueh.client.stub.GetCalcGroups")
    @ResponseWrapper(localName = "getCalcGroupsResponse", targetNamespace = "http://ueh.ws.okocits3.atp.asuneft.sng/", className = "sng.asuneft.atp.okocits3.ws.ueh.client.stub.GetCalcGroupsResponse")
    public List<CalcGroup> getCalcGroups(
        @WebParam(name = "filters", targetNamespace = "")
        List<CalcGroupRequestFilter> filters,
        @WebParam(name = "withlimit", targetNamespace = "")
        Boolean withlimit);

    /**
     * 
     * @param idOkoCalcGroup
     */
    @WebMethod
    @RequestWrapper(localName = "deleteCalcGroup", targetNamespace = "http://ueh.ws.okocits3.atp.asuneft.sng/", className = "sng.asuneft.atp.okocits3.ws.ueh.client.stub.DeleteCalcGroup")
    @ResponseWrapper(localName = "deleteCalcGroupResponse", targetNamespace = "http://ueh.ws.okocits3.atp.asuneft.sng/", className = "sng.asuneft.atp.okocits3.ws.ueh.client.stub.DeleteCalcGroupResponse")
    public void deleteCalcGroup(
        @WebParam(name = "idOkoCalcGroup", targetNamespace = "")
        int idOkoCalcGroup);

    /**
     * 
     * @param limits
     */
    @WebMethod
    @RequestWrapper(localName = "setLimits", targetNamespace = "http://ueh.ws.okocits3.atp.asuneft.sng/", className = "sng.asuneft.atp.okocits3.ws.ueh.client.stub.SetLimits")
    @ResponseWrapper(localName = "setLimitsResponse", targetNamespace = "http://ueh.ws.okocits3.atp.asuneft.sng/", className = "sng.asuneft.atp.okocits3.ws.ueh.client.stub.SetLimitsResponse")
    public void setLimits(
        @WebParam(name = "limits", targetNamespace = "")
        List<CalcLimit> limits);

}
