CONNECT 'jdbc:derby://localhost:1527//WORKDB/WEBDICOM;create=true';

CREATE TABLE WEBDICOM.DCMFILE (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DCM_FILE_NAME VARCHAR(512) NOT NULL,
	PATIENT_NAME VARCHAR(512) NOT NULL,
	PATIENT_BIRTH_DATE DATE NOT NULL,
	STUDY_DATE DATE NOT NULL,
	CONSTRAINT WEBDICOM.PK_DCMFILES PRIMARY KEY (ID),
	UNIQUE (DCM_FILE_NAME)
);


CREATE TABLE WEBDICOM.IMAGES (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	FID_DCMFILE INTEGER NOT NULL,	
	CONTENT_TYPE VARCHAR(512) NOT NULL,
	IMAGE_FILE_NAME VARCHAR(512) NOT NULL,
	CONSTRAINT WEBDICOM.PK_IMAGES PRIMARY KEY (ID),
	CONSTRAINT WEBDICOM.FK_IMAGES_DCMFILE FOREIGN KEY (FID_DCMFILE) REFERENCES WEBDICOM.DCMFILE (ID),
	UNIQUE (IMAGE_FILE_NAME)
); 
