#!/bin/sh
### ====================================================================== ###
##                                                                          ##
##  dcm4che2/dcmrcv  Launch Script                                          ##
##                                                                          ##
### ====================================================================== ###

### $Id: dcmrcv 11988 2009-07-24 13:13:57Z gunterze $ ###

MAIN_CLASS=org.psystems.dicom.daemon.Archive
MAIN_JAR=dcmarchive.jar
PID='/export/home/httpd/dicom/bin/dcmarchive.pid'


DIRNAME="`dirname "$0"`"

# OS specific support (must be 'true' or 'false').
cygwin=false;
case "`uname`" in
    CYGWIN*)
        cygwin=true
        ;;
esac

# For Cygwin, ensure paths are in UNIX format before anything is touched
if $cygwin ; then
    [ -n "$DCM4CHE_HOME" ] &&
        DCM4CHE_HOME=`cygpath --unix "$DCM4CHE_HOME"`
    [ -n "$JAVA_HOME" ] &&
        JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
fi

# Setup DCM4CHE_HOME
if [ "x$DCM4CHE_HOME" = "x" ]; then
    DCM4CHE_HOME=`cd "$DIRNAME"/..; pwd`
fi

# Setup the JVM
if [ "x$JAVA_HOME" != "x" ]; then
    JAVA=$JAVA_HOME/bin/java
else
    JAVA="java"
fi


# Setup the classpath
CP="$DCM4CHE_HOME/etc/"
CP="$CP:$DCM4CHE_HOME/lib/$MAIN_JAR"
CP="$CP:$DCM4CHE_HOME/lib/dcm4che-core-2.0.21.jar"
CP="$CP:$DCM4CHE_HOME/lib/dcm4che-filecache-2.0.21.jar"
CP="$CP:$DCM4CHE_HOME/lib/dcm4che-net-2.0.21.jar"
CP="$CP:$DCM4CHE_HOME/lib/slf4j-log4j12-1.5.0.jar"
CP="$CP:$DCM4CHE_HOME/lib/slf4j-api-1.5.0.jar"
CP="$CP:$DCM4CHE_HOME/lib/commons-cli-1.2.jar"
CP="$CP:$DCM4CHE_HOME/lib/derby.jar"
CP="$CP:$DCM4CHE_HOME/lib/derbyclient.jar"
CP="$CP:$DCM4CHE_HOME/lib/derbynet.jar"
CP="$CP:$DCM4CHE_HOME/lib/dcm4che-core-2.0.21.jar"
CP="$CP:$DCM4CHE_HOME/lib/dcm4che-imageio-2.0.21.jar"
CP="$CP:$DCM4CHE_HOME/lib/dcm4che-image-2.0.21.jar"
CP="$CP:$DCM4CHE_HOME/lib/dcm4che-filecache-2.0.21.jar"
CP="$CP:$DCM4CHE_HOME/lib/dcm4che-net-2.0.21.jar"
CP="$CP:$DCM4CHE_HOME/lib/commons-cli-1.2.jar"
CP="$CP:$DCM4CHE_HOME/lib/dcm4che-imageio-rle-2.0.21.jar"
CP="$CP:$DCM4CHE_HOME/lib/slf4j-api-1.5.0.jar"
CP="$CP:$DCM4CHE_HOME/lib/slf4j-log4j12-1.5.0.jar"
CP="$CP:$DCM4CHE_HOME/lib/org.apache.log4j_1.2.13.v200806030600.jar"
CP="$CP:$DCM4CHE_HOME/lib/jai_imageio.jar"
CP="$CP:$DCM4CHE_HOME/lib/slf4j-log4j12-1.5.0.jar"


# For Cygwin, switch paths to Windows format before running java
#if $cygwin; then
#    JAVA=`cygpath --path --windows "$JAVA"`
#    CP=`cygpath --path --windows "$CP"`
#fi

# Execute the JVM
$JAVA $JAVA_OPTS -cp "$CP" $MAIN_CLASS "$@" &


echo $! > $PID 