#!/bin/sh

jdk='/usr/bin/java -Xms32m -Xmx1536m'
filecfg=/export/home/soi/soiserver/server.bn.cfg
filepath=/export/home/soi/soiserver
libpath=/export/home/soi/lib
filelog=/var/log/soi/soiserver.errlog


if [ $1 ]
   	then 
cd $filepath;$jdk -cp $libpath/classes12.zip:$libpath/log4j-1.2.8.jar:$libpath/soiserver.jar:$libpath/jakarta-httpcore-4.0-alpha2.jar:$libpath/commons-dbcp-1.2.2.jar:$libpath/commons-pool-1.3.jar:$libpath/commons-collections-3.2.jar \
 -Djava.rmi.server.codebase=file://$libpath/soiserver.jar \
 -Djava.security.policy=$filepath/policy \
 -Dcom.sun.management.jmxremote.port=8085 \
 -Dcom.sun.management.jmxremote.ssl=false \
 -Dcom.sun.management.jmxremote.authenticate=false \
 com.asutp.webgroup.soiserver.StartServer $filecfg >>$filelog 2>&1 &

echo $! > $1 
   else
	echo "Can't start SOI. Not set pidpath" >> $filelog
fi
 